# It may be tempting to add parens around each individual clause in this expression, but Travis then builds pushes anyway
if: branch = master OR branch =~ ^features/ OR branch =~ ^release/ OR tag IS present
language: go
go: 1.13.4
sudo: true # give us 7.5GB and >2 bursted cores.
git:
  depth: false
before_install:
    - git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
    - source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
    - source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
install:
    - source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
    - curl -L https://get.pulumi.com/ | bash
    - export PATH=$HOME/.pulumi/bin:$PATH
    - wget -O /tmp/packr_2.7.1_linux_amd64.tar.gz https://github.com/gobuffalo/packr/releases/download/v2.7.1/packr_2.7.1_linux_amd64.tar.gz
    - tar -xvf /tmp/packr_2.7.1_linux_amd64.tar.gz -C /tmp
    - chmod +x /tmp/packr2
    - sudo mv /tmp/packr2 /usr/local/bin
before_script:
    - ${PULUMI_SCRIPTS}/ci/ensure-dependencies
script:
    - make travis_${TRAVIS_EVENT_TYPE}
after_failure:
    - ${PULUMI_SCRIPTS}/ci/upload-failed-tests
notifications:
    webhooks: https://zlmgkhmhjc.execute-api.us-west-2.amazonaws.com/stage/travis
