// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven
{
    public static class GetExternalIdentity
    {
        /// <summary>
        /// Maps an external service user to an Aiven user. 
        /// 
        /// **This resource is in the beta stage and may change without notice.** Set
        /// the `PROVIDER_AIVEN_ENABLE_BETA` environment variable to use the resource.
        /// </summary>
        public static Task<GetExternalIdentityResult> InvokeAsync(GetExternalIdentityArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetExternalIdentityResult>("aiven:index/getExternalIdentity:getExternalIdentity", args ?? new GetExternalIdentityArgs(), options.WithDefaults());

        /// <summary>
        /// Maps an external service user to an Aiven user. 
        /// 
        /// **This resource is in the beta stage and may change without notice.** Set
        /// the `PROVIDER_AIVEN_ENABLE_BETA` environment variable to use the resource.
        /// </summary>
        public static Output<GetExternalIdentityResult> Invoke(GetExternalIdentityInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetExternalIdentityResult>("aiven:index/getExternalIdentity:getExternalIdentity", args ?? new GetExternalIdentityInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetExternalIdentityArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the external service. The possible values are `github`.
        /// </summary>
        [Input("externalServiceName", required: true)]
        public string ExternalServiceName { get; set; } = null!;

        /// <summary>
        /// The user's ID on the external service.
        /// </summary>
        [Input("externalUserId", required: true)]
        public string ExternalUserId { get; set; } = null!;

        /// <summary>
        /// The Aiven user ID.
        /// </summary>
        [Input("internalUserId", required: true)]
        public string InternalUserId { get; set; } = null!;

        /// <summary>
        /// The ID of the Aiven organization that the user is part of.
        /// </summary>
        [Input("organizationId", required: true)]
        public string OrganizationId { get; set; } = null!;

        public GetExternalIdentityArgs()
        {
        }
        public static new GetExternalIdentityArgs Empty => new GetExternalIdentityArgs();
    }

    public sealed class GetExternalIdentityInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the external service. The possible values are `github`.
        /// </summary>
        [Input("externalServiceName", required: true)]
        public Input<string> ExternalServiceName { get; set; } = null!;

        /// <summary>
        /// The user's ID on the external service.
        /// </summary>
        [Input("externalUserId", required: true)]
        public Input<string> ExternalUserId { get; set; } = null!;

        /// <summary>
        /// The Aiven user ID.
        /// </summary>
        [Input("internalUserId", required: true)]
        public Input<string> InternalUserId { get; set; } = null!;

        /// <summary>
        /// The ID of the Aiven organization that the user is part of.
        /// </summary>
        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        public GetExternalIdentityInvokeArgs()
        {
        }
        public static new GetExternalIdentityInvokeArgs Empty => new GetExternalIdentityInvokeArgs();
    }


    [OutputType]
    public sealed class GetExternalIdentityResult
    {
        /// <summary>
        /// The name of the external service. The possible values are `github`.
        /// </summary>
        public readonly string ExternalServiceName;
        /// <summary>
        /// The user's ID on the external service.
        /// </summary>
        public readonly string ExternalUserId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The Aiven user ID.
        /// </summary>
        public readonly string InternalUserId;
        /// <summary>
        /// The ID of the Aiven organization that the user is part of.
        /// </summary>
        public readonly string OrganizationId;

        [OutputConstructor]
        private GetExternalIdentityResult(
            string externalServiceName,

            string externalUserId,

            string id,

            string internalUserId,

            string organizationId)
        {
            ExternalServiceName = externalServiceName;
            ExternalUserId = externalUserId;
            Id = id;
            InternalUserId = internalUserId;
            OrganizationId = organizationId;
        }
    }
}
