// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAwsVpcPeeringConnectionArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAwsVpcPeeringConnectionArgs Empty = new GetAwsVpcPeeringConnectionArgs();

    /**
     * AWS account ID. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="awsAccountId", required=true)
    private Output<String> awsAccountId;

    /**
     * @return AWS account ID. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> awsAccountId() {
        return this.awsAccountId;
    }

    /**
     * AWS VPC ID. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="awsVpcId", required=true)
    private Output<String> awsVpcId;

    /**
     * @return AWS VPC ID. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> awsVpcId() {
        return this.awsVpcId;
    }

    /**
     * The AWS region of the peered VPC, if different from the Aiven VPC region. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="awsVpcRegion", required=true)
    private Output<String> awsVpcRegion;

    /**
     * @return The AWS region of the peered VPC, if different from the Aiven VPC region. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> awsVpcRegion() {
        return this.awsVpcRegion;
    }

    /**
     * The ID of the Aiven VPC. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="vpcId", required=true)
    private Output<String> vpcId;

    /**
     * @return The ID of the Aiven VPC. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> vpcId() {
        return this.vpcId;
    }

    private GetAwsVpcPeeringConnectionArgs() {}

    private GetAwsVpcPeeringConnectionArgs(GetAwsVpcPeeringConnectionArgs $) {
        this.awsAccountId = $.awsAccountId;
        this.awsVpcId = $.awsVpcId;
        this.awsVpcRegion = $.awsVpcRegion;
        this.vpcId = $.vpcId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAwsVpcPeeringConnectionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAwsVpcPeeringConnectionArgs $;

        public Builder() {
            $ = new GetAwsVpcPeeringConnectionArgs();
        }

        public Builder(GetAwsVpcPeeringConnectionArgs defaults) {
            $ = new GetAwsVpcPeeringConnectionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param awsAccountId AWS account ID. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsAccountId(Output<String> awsAccountId) {
            $.awsAccountId = awsAccountId;
            return this;
        }

        /**
         * @param awsAccountId AWS account ID. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsAccountId(String awsAccountId) {
            return awsAccountId(Output.of(awsAccountId));
        }

        /**
         * @param awsVpcId AWS VPC ID. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsVpcId(Output<String> awsVpcId) {
            $.awsVpcId = awsVpcId;
            return this;
        }

        /**
         * @param awsVpcId AWS VPC ID. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsVpcId(String awsVpcId) {
            return awsVpcId(Output.of(awsVpcId));
        }

        /**
         * @param awsVpcRegion The AWS region of the peered VPC, if different from the Aiven VPC region. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsVpcRegion(Output<String> awsVpcRegion) {
            $.awsVpcRegion = awsVpcRegion;
            return this;
        }

        /**
         * @param awsVpcRegion The AWS region of the peered VPC, if different from the Aiven VPC region. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder awsVpcRegion(String awsVpcRegion) {
            return awsVpcRegion(Output.of(awsVpcRegion));
        }

        /**
         * @param vpcId The ID of the Aiven VPC. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder vpcId(Output<String> vpcId) {
            $.vpcId = vpcId;
            return this;
        }

        /**
         * @param vpcId The ID of the Aiven VPC. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder vpcId(String vpcId) {
            return vpcId(Output.of(vpcId));
        }

        public GetAwsVpcPeeringConnectionArgs build() {
            if ($.awsAccountId == null) {
                throw new MissingRequiredPropertyException("GetAwsVpcPeeringConnectionArgs", "awsAccountId");
            }
            if ($.awsVpcId == null) {
                throw new MissingRequiredPropertyException("GetAwsVpcPeeringConnectionArgs", "awsVpcId");
            }
            if ($.awsVpcRegion == null) {
                throw new MissingRequiredPropertyException("GetAwsVpcPeeringConnectionArgs", "awsVpcRegion");
            }
            if ($.vpcId == null) {
                throw new MissingRequiredPropertyException("GetAwsVpcPeeringConnectionArgs", "vpcId");
            }
            return $;
        }
    }

}
