// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.aiven.inputs.GetAwsPrivatelinkTimeouts;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAwsPrivatelinkPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAwsPrivatelinkPlainArgs Empty = new GetAwsPrivatelinkPlainArgs();

    /**
     * Project name.
     * 
     */
    @Import(name="project", required=true)
    private String project;

    /**
     * @return Project name.
     * 
     */
    public String project() {
        return this.project;
    }

    /**
     * Service name.
     * 
     */
    @Import(name="serviceName", required=true)
    private String serviceName;

    /**
     * @return Service name.
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }

    @Import(name="timeouts")
    private @Nullable GetAwsPrivatelinkTimeouts timeouts;

    public Optional<GetAwsPrivatelinkTimeouts> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    private GetAwsPrivatelinkPlainArgs() {}

    private GetAwsPrivatelinkPlainArgs(GetAwsPrivatelinkPlainArgs $) {
        this.project = $.project;
        this.serviceName = $.serviceName;
        this.timeouts = $.timeouts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAwsPrivatelinkPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAwsPrivatelinkPlainArgs $;

        public Builder() {
            $ = new GetAwsPrivatelinkPlainArgs();
        }

        public Builder(GetAwsPrivatelinkPlainArgs defaults) {
            $ = new GetAwsPrivatelinkPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param project Project name.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            $.project = project;
            return this;
        }

        /**
         * @param serviceName Service name.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        public Builder timeouts(@Nullable GetAwsPrivatelinkTimeouts timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public GetAwsPrivatelinkPlainArgs build() {
            if ($.project == null) {
                throw new MissingRequiredPropertyException("GetAwsPrivatelinkPlainArgs", "project");
            }
            if ($.serviceName == null) {
                throw new MissingRequiredPropertyException("GetAwsPrivatelinkPlainArgs", "serviceName");
            }
            return $;
        }
    }

}
