// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.aiven.inputs.GetOrganizationUserGroupListTimeoutsArgs;
import com.pulumi.aiven.inputs.GetOrganizationUserGroupListUserGroupArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetOrganizationUserGroupListArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetOrganizationUserGroupListArgs Empty = new GetOrganizationUserGroupListArgs();

    /**
     * ID of an organization.
     * 
     */
    @Import(name="organizationId", required=true)
    private Output<String> organizationId;

    /**
     * @return ID of an organization.
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }

    @Import(name="timeouts")
    private @Nullable Output<GetOrganizationUserGroupListTimeoutsArgs> timeouts;

    public Optional<Output<GetOrganizationUserGroupListTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    /**
     * User Groups.
     * 
     */
    @Import(name="userGroups")
    private @Nullable Output<List<GetOrganizationUserGroupListUserGroupArgs>> userGroups;

    /**
     * @return User Groups.
     * 
     */
    public Optional<Output<List<GetOrganizationUserGroupListUserGroupArgs>>> userGroups() {
        return Optional.ofNullable(this.userGroups);
    }

    private GetOrganizationUserGroupListArgs() {}

    private GetOrganizationUserGroupListArgs(GetOrganizationUserGroupListArgs $) {
        this.organizationId = $.organizationId;
        this.timeouts = $.timeouts;
        this.userGroups = $.userGroups;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetOrganizationUserGroupListArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetOrganizationUserGroupListArgs $;

        public Builder() {
            $ = new GetOrganizationUserGroupListArgs();
        }

        public Builder(GetOrganizationUserGroupListArgs defaults) {
            $ = new GetOrganizationUserGroupListArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param organizationId ID of an organization.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId ID of an organization.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        public Builder timeouts(@Nullable Output<GetOrganizationUserGroupListTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(GetOrganizationUserGroupListTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        /**
         * @param userGroups User Groups.
         * 
         * @return builder
         * 
         */
        public Builder userGroups(@Nullable Output<List<GetOrganizationUserGroupListUserGroupArgs>> userGroups) {
            $.userGroups = userGroups;
            return this;
        }

        /**
         * @param userGroups User Groups.
         * 
         * @return builder
         * 
         */
        public Builder userGroups(List<GetOrganizationUserGroupListUserGroupArgs> userGroups) {
            return userGroups(Output.of(userGroups));
        }

        /**
         * @param userGroups User Groups.
         * 
         * @return builder
         * 
         */
        public Builder userGroups(GetOrganizationUserGroupListUserGroupArgs... userGroups) {
            return userGroups(List.of(userGroups));
        }

        public GetOrganizationUserGroupListArgs build() {
            if ($.organizationId == null) {
                throw new MissingRequiredPropertyException("GetOrganizationUserGroupListArgs", "organizationId");
            }
            return $;
        }
    }

}
