// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.aiven.inputs.KafkaComponentArgs;
import com.pulumi.aiven.inputs.KafkaKafkaArgs;
import com.pulumi.aiven.inputs.KafkaKafkaUserConfigArgs;
import com.pulumi.aiven.inputs.KafkaServiceIntegrationArgs;
import com.pulumi.aiven.inputs.KafkaTagArgs;
import com.pulumi.aiven.inputs.KafkaTechEmailArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KafkaState extends com.pulumi.resources.ResourceArgs {

    public static final KafkaState Empty = new KafkaState();

    /**
     * Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
     * 
     */
    @Import(name="additionalDiskSpace")
    private @Nullable Output<String> additionalDiskSpace;

    /**
     * @return Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
     * 
     */
    public Optional<Output<String>> additionalDiskSpace() {
        return Optional.ofNullable(this.additionalDiskSpace);
    }

    /**
     * Defines where the cloud provider and region where the service is hosted in. This can be changed freely after service is created. Changing the value will trigger a potentially lengthy migration process for the service. Format is cloud provider name (`aws`, `azure`, `do` `google`, `upcloud`, etc.), dash, and the cloud provider specific region name. These are documented on each Cloud provider&#39;s own support articles, like [here for Google](https://cloud.google.com/compute/docs/regions-zones/) and [here for AWS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).
     * 
     */
    @Import(name="cloudName")
    private @Nullable Output<String> cloudName;

    /**
     * @return Defines where the cloud provider and region where the service is hosted in. This can be changed freely after service is created. Changing the value will trigger a potentially lengthy migration process for the service. Format is cloud provider name (`aws`, `azure`, `do` `google`, `upcloud`, etc.), dash, and the cloud provider specific region name. These are documented on each Cloud provider&#39;s own support articles, like [here for Google](https://cloud.google.com/compute/docs/regions-zones/) and [here for AWS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).
     * 
     */
    public Optional<Output<String>> cloudName() {
        return Optional.ofNullable(this.cloudName);
    }

    /**
     * Service component information objects
     * 
     */
    @Import(name="components")
    private @Nullable Output<List<KafkaComponentArgs>> components;

    /**
     * @return Service component information objects
     * 
     */
    public Optional<Output<List<KafkaComponentArgs>>> components() {
        return Optional.ofNullable(this.components);
    }

    /**
     * Create default wildcard Kafka ACL
     * 
     */
    @Import(name="defaultAcl")
    private @Nullable Output<Boolean> defaultAcl;

    /**
     * @return Create default wildcard Kafka ACL
     * 
     */
    public Optional<Output<Boolean>> defaultAcl() {
        return Optional.ofNullable(this.defaultAcl);
    }

    /**
     * Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
     * 
     * @deprecated
     * This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan.
     * 
     */
    @Deprecated /* This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan. */
    @Import(name="diskSpace")
    private @Nullable Output<String> diskSpace;

    /**
     * @return Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
     * 
     * @deprecated
     * This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan.
     * 
     */
    @Deprecated /* This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan. */
    public Optional<Output<String>> diskSpace() {
        return Optional.ofNullable(this.diskSpace);
    }

    /**
     * The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
     * 
     */
    @Import(name="diskSpaceCap")
    private @Nullable Output<String> diskSpaceCap;

    /**
     * @return The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
     * 
     */
    public Optional<Output<String>> diskSpaceCap() {
        return Optional.ofNullable(this.diskSpaceCap);
    }

    /**
     * The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `disk_space`
     * 
     */
    @Import(name="diskSpaceDefault")
    private @Nullable Output<String> diskSpaceDefault;

    /**
     * @return The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `disk_space`
     * 
     */
    public Optional<Output<String>> diskSpaceDefault() {
        return Optional.ofNullable(this.diskSpaceDefault);
    }

    /**
     * The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `disk_space` needs to increment from `disk_space_default` by increments of this size.
     * 
     */
    @Import(name="diskSpaceStep")
    private @Nullable Output<String> diskSpaceStep;

    /**
     * @return The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `disk_space` needs to increment from `disk_space_default` by increments of this size.
     * 
     */
    public Optional<Output<String>> diskSpaceStep() {
        return Optional.ofNullable(this.diskSpaceStep);
    }

    /**
     * Disk space that service is currently using
     * 
     */
    @Import(name="diskSpaceUsed")
    private @Nullable Output<String> diskSpaceUsed;

    /**
     * @return Disk space that service is currently using
     * 
     */
    public Optional<Output<String>> diskSpaceUsed() {
        return Optional.ofNullable(this.diskSpaceUsed);
    }

    /**
     * Kafka user configurable settings
     * 
     */
    @Import(name="kafkaUserConfig")
    private @Nullable Output<KafkaKafkaUserConfigArgs> kafkaUserConfig;

    /**
     * @return Kafka user configurable settings
     * 
     */
    public Optional<Output<KafkaKafkaUserConfigArgs>> kafkaUserConfig() {
        return Optional.ofNullable(this.kafkaUserConfig);
    }

    /**
     * Kafka broker configuration values
     * 
     */
    @Import(name="kafkas")
    private @Nullable Output<List<KafkaKafkaArgs>> kafkas;

    /**
     * @return Kafka broker configuration values
     * 
     */
    public Optional<Output<List<KafkaKafkaArgs>>> kafkas() {
        return Optional.ofNullable(this.kafkas);
    }

    /**
     * Switch the service to use Karapace for schema registry and REST proxy
     * 
     * @deprecated
     * Usage of this field is discouraged.
     * 
     */
    @Deprecated /* Usage of this field is discouraged. */
    @Import(name="karapace")
    private @Nullable Output<Boolean> karapace;

    /**
     * @return Switch the service to use Karapace for schema registry and REST proxy
     * 
     * @deprecated
     * Usage of this field is discouraged.
     * 
     */
    @Deprecated /* Usage of this field is discouraged. */
    public Optional<Output<Boolean>> karapace() {
        return Optional.ofNullable(this.karapace);
    }

    /**
     * Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
     * 
     */
    @Import(name="maintenanceWindowDow")
    private @Nullable Output<String> maintenanceWindowDow;

    /**
     * @return Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
     * 
     */
    public Optional<Output<String>> maintenanceWindowDow() {
        return Optional.ofNullable(this.maintenanceWindowDow);
    }

    /**
     * Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
     * 
     */
    @Import(name="maintenanceWindowTime")
    private @Nullable Output<String> maintenanceWindowTime;

    /**
     * @return Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
     * 
     */
    public Optional<Output<String>> maintenanceWindowTime() {
        return Optional.ofNullable(this.maintenanceWindowTime);
    }

    /**
     * Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seem from the [Aiven pricing page](https://aiven.io/pricing).
     * 
     */
    @Import(name="plan")
    private @Nullable Output<String> plan;

    /**
     * @return Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seem from the [Aiven pricing page](https://aiven.io/pricing).
     * 
     */
    public Optional<Output<String>> plan() {
        return Optional.ofNullable(this.plan);
    }

    /**
     * Identifies the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="project")
    private @Nullable Output<String> project;

    /**
     * @return Identifies the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
     * 
     */
    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * Specifies the VPC the service should run in. If the value is not set the service is not run inside a VPC. When set, the value should be given as a reference to set up dependencies correctly and the VPC must be in the same cloud and region as the service itself. Project can be freely moved to and from VPC after creation but doing so triggers migration to new servers so the operation can take significant amount of time to complete if the service has a lot of data.
     * 
     */
    @Import(name="projectVpcId")
    private @Nullable Output<String> projectVpcId;

    /**
     * @return Specifies the VPC the service should run in. If the value is not set the service is not run inside a VPC. When set, the value should be given as a reference to set up dependencies correctly and the VPC must be in the same cloud and region as the service itself. Project can be freely moved to and from VPC after creation but doing so triggers migration to new servers so the operation can take significant amount of time to complete if the service has a lot of data.
     * 
     */
    public Optional<Output<String>> projectVpcId() {
        return Optional.ofNullable(this.projectVpcId);
    }

    /**
     * The hostname of the service.
     * 
     */
    @Import(name="serviceHost")
    private @Nullable Output<String> serviceHost;

    /**
     * @return The hostname of the service.
     * 
     */
    public Optional<Output<String>> serviceHost() {
        return Optional.ofNullable(this.serviceHost);
    }

    /**
     * Service integrations to specify when creating a service. Not applied after initial service creation
     * 
     */
    @Import(name="serviceIntegrations")
    private @Nullable Output<List<KafkaServiceIntegrationArgs>> serviceIntegrations;

    /**
     * @return Service integrations to specify when creating a service. Not applied after initial service creation
     * 
     */
    public Optional<Output<List<KafkaServiceIntegrationArgs>>> serviceIntegrations() {
        return Optional.ofNullable(this.serviceIntegrations);
    }

    /**
     * Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
     * 
     */
    @Import(name="serviceName")
    private @Nullable Output<String> serviceName;

    /**
     * @return Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
     * 
     */
    public Optional<Output<String>> serviceName() {
        return Optional.ofNullable(this.serviceName);
    }

    /**
     * Password used for connecting to the service, if applicable
     * 
     */
    @Import(name="servicePassword")
    private @Nullable Output<String> servicePassword;

    /**
     * @return Password used for connecting to the service, if applicable
     * 
     */
    public Optional<Output<String>> servicePassword() {
        return Optional.ofNullable(this.servicePassword);
    }

    /**
     * The port of the service
     * 
     */
    @Import(name="servicePort")
    private @Nullable Output<Integer> servicePort;

    /**
     * @return The port of the service
     * 
     */
    public Optional<Output<Integer>> servicePort() {
        return Optional.ofNullable(this.servicePort);
    }

    /**
     * Aiven internal service type code
     * 
     */
    @Import(name="serviceType")
    private @Nullable Output<String> serviceType;

    /**
     * @return Aiven internal service type code
     * 
     */
    public Optional<Output<String>> serviceType() {
        return Optional.ofNullable(this.serviceType);
    }

    /**
     * URI for connecting to the service. Service specific info is under &#34;kafka&#34;, &#34;pg&#34;, etc.
     * 
     */
    @Import(name="serviceUri")
    private @Nullable Output<String> serviceUri;

    /**
     * @return URI for connecting to the service. Service specific info is under &#34;kafka&#34;, &#34;pg&#34;, etc.
     * 
     */
    public Optional<Output<String>> serviceUri() {
        return Optional.ofNullable(this.serviceUri);
    }

    /**
     * Username used for connecting to the service, if applicable
     * 
     */
    @Import(name="serviceUsername")
    private @Nullable Output<String> serviceUsername;

    /**
     * @return Username used for connecting to the service, if applicable
     * 
     */
    public Optional<Output<String>> serviceUsername() {
        return Optional.ofNullable(this.serviceUsername);
    }

    /**
     * Service state. One of `POWEROFF`, `REBALANCING`, `REBUILDING` or `RUNNING`
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return Service state. One of `POWEROFF`, `REBALANCING`, `REBUILDING` or `RUNNING`
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    /**
     * Use static public IP addresses.
     * 
     */
    @Import(name="staticIps")
    private @Nullable Output<List<String>> staticIps;

    /**
     * @return Use static public IP addresses.
     * 
     */
    public Optional<Output<List<String>>> staticIps() {
        return Optional.ofNullable(this.staticIps);
    }

    /**
     * Tags are key-value pairs that allow you to categorize services.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<KafkaTagArgs>> tags;

    /**
     * @return Tags are key-value pairs that allow you to categorize services.
     * 
     */
    public Optional<Output<List<KafkaTagArgs>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * Defines the email addresses that will receive alerts about upcoming maintenance updates or warnings about service instability.
     * 
     */
    @Import(name="techEmails")
    private @Nullable Output<List<KafkaTechEmailArgs>> techEmails;

    /**
     * @return Defines the email addresses that will receive alerts about upcoming maintenance updates or warnings about service instability.
     * 
     */
    public Optional<Output<List<KafkaTechEmailArgs>>> techEmails() {
        return Optional.ofNullable(this.techEmails);
    }

    /**
     * Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
     * 
     */
    @Import(name="terminationProtection")
    private @Nullable Output<Boolean> terminationProtection;

    /**
     * @return Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
     * 
     */
    public Optional<Output<Boolean>> terminationProtection() {
        return Optional.ofNullable(this.terminationProtection);
    }

    private KafkaState() {}

    private KafkaState(KafkaState $) {
        this.additionalDiskSpace = $.additionalDiskSpace;
        this.cloudName = $.cloudName;
        this.components = $.components;
        this.defaultAcl = $.defaultAcl;
        this.diskSpace = $.diskSpace;
        this.diskSpaceCap = $.diskSpaceCap;
        this.diskSpaceDefault = $.diskSpaceDefault;
        this.diskSpaceStep = $.diskSpaceStep;
        this.diskSpaceUsed = $.diskSpaceUsed;
        this.kafkaUserConfig = $.kafkaUserConfig;
        this.kafkas = $.kafkas;
        this.karapace = $.karapace;
        this.maintenanceWindowDow = $.maintenanceWindowDow;
        this.maintenanceWindowTime = $.maintenanceWindowTime;
        this.plan = $.plan;
        this.project = $.project;
        this.projectVpcId = $.projectVpcId;
        this.serviceHost = $.serviceHost;
        this.serviceIntegrations = $.serviceIntegrations;
        this.serviceName = $.serviceName;
        this.servicePassword = $.servicePassword;
        this.servicePort = $.servicePort;
        this.serviceType = $.serviceType;
        this.serviceUri = $.serviceUri;
        this.serviceUsername = $.serviceUsername;
        this.state = $.state;
        this.staticIps = $.staticIps;
        this.tags = $.tags;
        this.techEmails = $.techEmails;
        this.terminationProtection = $.terminationProtection;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KafkaState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KafkaState $;

        public Builder() {
            $ = new KafkaState();
        }

        public Builder(KafkaState defaults) {
            $ = new KafkaState(Objects.requireNonNull(defaults));
        }

        /**
         * @param additionalDiskSpace Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
         * 
         * @return builder
         * 
         */
        public Builder additionalDiskSpace(@Nullable Output<String> additionalDiskSpace) {
            $.additionalDiskSpace = additionalDiskSpace;
            return this;
        }

        /**
         * @param additionalDiskSpace Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
         * 
         * @return builder
         * 
         */
        public Builder additionalDiskSpace(String additionalDiskSpace) {
            return additionalDiskSpace(Output.of(additionalDiskSpace));
        }

        /**
         * @param cloudName Defines where the cloud provider and region where the service is hosted in. This can be changed freely after service is created. Changing the value will trigger a potentially lengthy migration process for the service. Format is cloud provider name (`aws`, `azure`, `do` `google`, `upcloud`, etc.), dash, and the cloud provider specific region name. These are documented on each Cloud provider&#39;s own support articles, like [here for Google](https://cloud.google.com/compute/docs/regions-zones/) and [here for AWS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).
         * 
         * @return builder
         * 
         */
        public Builder cloudName(@Nullable Output<String> cloudName) {
            $.cloudName = cloudName;
            return this;
        }

        /**
         * @param cloudName Defines where the cloud provider and region where the service is hosted in. This can be changed freely after service is created. Changing the value will trigger a potentially lengthy migration process for the service. Format is cloud provider name (`aws`, `azure`, `do` `google`, `upcloud`, etc.), dash, and the cloud provider specific region name. These are documented on each Cloud provider&#39;s own support articles, like [here for Google](https://cloud.google.com/compute/docs/regions-zones/) and [here for AWS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html).
         * 
         * @return builder
         * 
         */
        public Builder cloudName(String cloudName) {
            return cloudName(Output.of(cloudName));
        }

        /**
         * @param components Service component information objects
         * 
         * @return builder
         * 
         */
        public Builder components(@Nullable Output<List<KafkaComponentArgs>> components) {
            $.components = components;
            return this;
        }

        /**
         * @param components Service component information objects
         * 
         * @return builder
         * 
         */
        public Builder components(List<KafkaComponentArgs> components) {
            return components(Output.of(components));
        }

        /**
         * @param components Service component information objects
         * 
         * @return builder
         * 
         */
        public Builder components(KafkaComponentArgs... components) {
            return components(List.of(components));
        }

        /**
         * @param defaultAcl Create default wildcard Kafka ACL
         * 
         * @return builder
         * 
         */
        public Builder defaultAcl(@Nullable Output<Boolean> defaultAcl) {
            $.defaultAcl = defaultAcl;
            return this;
        }

        /**
         * @param defaultAcl Create default wildcard Kafka ACL
         * 
         * @return builder
         * 
         */
        public Builder defaultAcl(Boolean defaultAcl) {
            return defaultAcl(Output.of(defaultAcl));
        }

        /**
         * @param diskSpace Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
         * 
         * @return builder
         * 
         * @deprecated
         * This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan.
         * 
         */
        @Deprecated /* This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan. */
        public Builder diskSpace(@Nullable Output<String> diskSpace) {
            $.diskSpace = diskSpace;
            return this;
        }

        /**
         * @param diskSpace Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.
         * 
         * @return builder
         * 
         * @deprecated
         * This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan.
         * 
         */
        @Deprecated /* This will be removed in v5.0.0. Please use `additional_disk_space` to specify the space to be added to the default `disk_space` defined by the plan. */
        public Builder diskSpace(String diskSpace) {
            return diskSpace(Output.of(diskSpace));
        }

        /**
         * @param diskSpaceCap The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceCap(@Nullable Output<String> diskSpaceCap) {
            $.diskSpaceCap = diskSpaceCap;
            return this;
        }

        /**
         * @param diskSpaceCap The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceCap(String diskSpaceCap) {
            return diskSpaceCap(Output.of(diskSpaceCap));
        }

        /**
         * @param diskSpaceDefault The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `disk_space`
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceDefault(@Nullable Output<String> diskSpaceDefault) {
            $.diskSpaceDefault = diskSpaceDefault;
            return this;
        }

        /**
         * @param diskSpaceDefault The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `disk_space`
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceDefault(String diskSpaceDefault) {
            return diskSpaceDefault(Output.of(diskSpaceDefault));
        }

        /**
         * @param diskSpaceStep The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `disk_space` needs to increment from `disk_space_default` by increments of this size.
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceStep(@Nullable Output<String> diskSpaceStep) {
            $.diskSpaceStep = diskSpaceStep;
            return this;
        }

        /**
         * @param diskSpaceStep The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `disk_space` needs to increment from `disk_space_default` by increments of this size.
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceStep(String diskSpaceStep) {
            return diskSpaceStep(Output.of(diskSpaceStep));
        }

        /**
         * @param diskSpaceUsed Disk space that service is currently using
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceUsed(@Nullable Output<String> diskSpaceUsed) {
            $.diskSpaceUsed = diskSpaceUsed;
            return this;
        }

        /**
         * @param diskSpaceUsed Disk space that service is currently using
         * 
         * @return builder
         * 
         */
        public Builder diskSpaceUsed(String diskSpaceUsed) {
            return diskSpaceUsed(Output.of(diskSpaceUsed));
        }

        /**
         * @param kafkaUserConfig Kafka user configurable settings
         * 
         * @return builder
         * 
         */
        public Builder kafkaUserConfig(@Nullable Output<KafkaKafkaUserConfigArgs> kafkaUserConfig) {
            $.kafkaUserConfig = kafkaUserConfig;
            return this;
        }

        /**
         * @param kafkaUserConfig Kafka user configurable settings
         * 
         * @return builder
         * 
         */
        public Builder kafkaUserConfig(KafkaKafkaUserConfigArgs kafkaUserConfig) {
            return kafkaUserConfig(Output.of(kafkaUserConfig));
        }

        /**
         * @param kafkas Kafka broker configuration values
         * 
         * @return builder
         * 
         */
        public Builder kafkas(@Nullable Output<List<KafkaKafkaArgs>> kafkas) {
            $.kafkas = kafkas;
            return this;
        }

        /**
         * @param kafkas Kafka broker configuration values
         * 
         * @return builder
         * 
         */
        public Builder kafkas(List<KafkaKafkaArgs> kafkas) {
            return kafkas(Output.of(kafkas));
        }

        /**
         * @param kafkas Kafka broker configuration values
         * 
         * @return builder
         * 
         */
        public Builder kafkas(KafkaKafkaArgs... kafkas) {
            return kafkas(List.of(kafkas));
        }

        /**
         * @param karapace Switch the service to use Karapace for schema registry and REST proxy
         * 
         * @return builder
         * 
         * @deprecated
         * Usage of this field is discouraged.
         * 
         */
        @Deprecated /* Usage of this field is discouraged. */
        public Builder karapace(@Nullable Output<Boolean> karapace) {
            $.karapace = karapace;
            return this;
        }

        /**
         * @param karapace Switch the service to use Karapace for schema registry and REST proxy
         * 
         * @return builder
         * 
         * @deprecated
         * Usage of this field is discouraged.
         * 
         */
        @Deprecated /* Usage of this field is discouraged. */
        public Builder karapace(Boolean karapace) {
            return karapace(Output.of(karapace));
        }

        /**
         * @param maintenanceWindowDow Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindowDow(@Nullable Output<String> maintenanceWindowDow) {
            $.maintenanceWindowDow = maintenanceWindowDow;
            return this;
        }

        /**
         * @param maintenanceWindowDow Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindowDow(String maintenanceWindowDow) {
            return maintenanceWindowDow(Output.of(maintenanceWindowDow));
        }

        /**
         * @param maintenanceWindowTime Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindowTime(@Nullable Output<String> maintenanceWindowTime) {
            $.maintenanceWindowTime = maintenanceWindowTime;
            return this;
        }

        /**
         * @param maintenanceWindowTime Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindowTime(String maintenanceWindowTime) {
            return maintenanceWindowTime(Output.of(maintenanceWindowTime));
        }

        /**
         * @param plan Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seem from the [Aiven pricing page](https://aiven.io/pricing).
         * 
         * @return builder
         * 
         */
        public Builder plan(@Nullable Output<String> plan) {
            $.plan = plan;
            return this;
        }

        /**
         * @param plan Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seem from the [Aiven pricing page](https://aiven.io/pricing).
         * 
         * @return builder
         * 
         */
        public Builder plan(String plan) {
            return plan(Output.of(plan));
        }

        /**
         * @param project Identifies the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project Identifies the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param projectVpcId Specifies the VPC the service should run in. If the value is not set the service is not run inside a VPC. When set, the value should be given as a reference to set up dependencies correctly and the VPC must be in the same cloud and region as the service itself. Project can be freely moved to and from VPC after creation but doing so triggers migration to new servers so the operation can take significant amount of time to complete if the service has a lot of data.
         * 
         * @return builder
         * 
         */
        public Builder projectVpcId(@Nullable Output<String> projectVpcId) {
            $.projectVpcId = projectVpcId;
            return this;
        }

        /**
         * @param projectVpcId Specifies the VPC the service should run in. If the value is not set the service is not run inside a VPC. When set, the value should be given as a reference to set up dependencies correctly and the VPC must be in the same cloud and region as the service itself. Project can be freely moved to and from VPC after creation but doing so triggers migration to new servers so the operation can take significant amount of time to complete if the service has a lot of data.
         * 
         * @return builder
         * 
         */
        public Builder projectVpcId(String projectVpcId) {
            return projectVpcId(Output.of(projectVpcId));
        }

        /**
         * @param serviceHost The hostname of the service.
         * 
         * @return builder
         * 
         */
        public Builder serviceHost(@Nullable Output<String> serviceHost) {
            $.serviceHost = serviceHost;
            return this;
        }

        /**
         * @param serviceHost The hostname of the service.
         * 
         * @return builder
         * 
         */
        public Builder serviceHost(String serviceHost) {
            return serviceHost(Output.of(serviceHost));
        }

        /**
         * @param serviceIntegrations Service integrations to specify when creating a service. Not applied after initial service creation
         * 
         * @return builder
         * 
         */
        public Builder serviceIntegrations(@Nullable Output<List<KafkaServiceIntegrationArgs>> serviceIntegrations) {
            $.serviceIntegrations = serviceIntegrations;
            return this;
        }

        /**
         * @param serviceIntegrations Service integrations to specify when creating a service. Not applied after initial service creation
         * 
         * @return builder
         * 
         */
        public Builder serviceIntegrations(List<KafkaServiceIntegrationArgs> serviceIntegrations) {
            return serviceIntegrations(Output.of(serviceIntegrations));
        }

        /**
         * @param serviceIntegrations Service integrations to specify when creating a service. Not applied after initial service creation
         * 
         * @return builder
         * 
         */
        public Builder serviceIntegrations(KafkaServiceIntegrationArgs... serviceIntegrations) {
            return serviceIntegrations(List.of(serviceIntegrations));
        }

        /**
         * @param serviceName Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(@Nullable Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        /**
         * @param servicePassword Password used for connecting to the service, if applicable
         * 
         * @return builder
         * 
         */
        public Builder servicePassword(@Nullable Output<String> servicePassword) {
            $.servicePassword = servicePassword;
            return this;
        }

        /**
         * @param servicePassword Password used for connecting to the service, if applicable
         * 
         * @return builder
         * 
         */
        public Builder servicePassword(String servicePassword) {
            return servicePassword(Output.of(servicePassword));
        }

        /**
         * @param servicePort The port of the service
         * 
         * @return builder
         * 
         */
        public Builder servicePort(@Nullable Output<Integer> servicePort) {
            $.servicePort = servicePort;
            return this;
        }

        /**
         * @param servicePort The port of the service
         * 
         * @return builder
         * 
         */
        public Builder servicePort(Integer servicePort) {
            return servicePort(Output.of(servicePort));
        }

        /**
         * @param serviceType Aiven internal service type code
         * 
         * @return builder
         * 
         */
        public Builder serviceType(@Nullable Output<String> serviceType) {
            $.serviceType = serviceType;
            return this;
        }

        /**
         * @param serviceType Aiven internal service type code
         * 
         * @return builder
         * 
         */
        public Builder serviceType(String serviceType) {
            return serviceType(Output.of(serviceType));
        }

        /**
         * @param serviceUri URI for connecting to the service. Service specific info is under &#34;kafka&#34;, &#34;pg&#34;, etc.
         * 
         * @return builder
         * 
         */
        public Builder serviceUri(@Nullable Output<String> serviceUri) {
            $.serviceUri = serviceUri;
            return this;
        }

        /**
         * @param serviceUri URI for connecting to the service. Service specific info is under &#34;kafka&#34;, &#34;pg&#34;, etc.
         * 
         * @return builder
         * 
         */
        public Builder serviceUri(String serviceUri) {
            return serviceUri(Output.of(serviceUri));
        }

        /**
         * @param serviceUsername Username used for connecting to the service, if applicable
         * 
         * @return builder
         * 
         */
        public Builder serviceUsername(@Nullable Output<String> serviceUsername) {
            $.serviceUsername = serviceUsername;
            return this;
        }

        /**
         * @param serviceUsername Username used for connecting to the service, if applicable
         * 
         * @return builder
         * 
         */
        public Builder serviceUsername(String serviceUsername) {
            return serviceUsername(Output.of(serviceUsername));
        }

        /**
         * @param state Service state. One of `POWEROFF`, `REBALANCING`, `REBUILDING` or `RUNNING`
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state Service state. One of `POWEROFF`, `REBALANCING`, `REBUILDING` or `RUNNING`
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        /**
         * @param staticIps Use static public IP addresses.
         * 
         * @return builder
         * 
         */
        public Builder staticIps(@Nullable Output<List<String>> staticIps) {
            $.staticIps = staticIps;
            return this;
        }

        /**
         * @param staticIps Use static public IP addresses.
         * 
         * @return builder
         * 
         */
        public Builder staticIps(List<String> staticIps) {
            return staticIps(Output.of(staticIps));
        }

        /**
         * @param staticIps Use static public IP addresses.
         * 
         * @return builder
         * 
         */
        public Builder staticIps(String... staticIps) {
            return staticIps(List.of(staticIps));
        }

        /**
         * @param tags Tags are key-value pairs that allow you to categorize services.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<KafkaTagArgs>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Tags are key-value pairs that allow you to categorize services.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<KafkaTagArgs> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags Tags are key-value pairs that allow you to categorize services.
         * 
         * @return builder
         * 
         */
        public Builder tags(KafkaTagArgs... tags) {
            return tags(List.of(tags));
        }

        /**
         * @param techEmails Defines the email addresses that will receive alerts about upcoming maintenance updates or warnings about service instability.
         * 
         * @return builder
         * 
         */
        public Builder techEmails(@Nullable Output<List<KafkaTechEmailArgs>> techEmails) {
            $.techEmails = techEmails;
            return this;
        }

        /**
         * @param techEmails Defines the email addresses that will receive alerts about upcoming maintenance updates or warnings about service instability.
         * 
         * @return builder
         * 
         */
        public Builder techEmails(List<KafkaTechEmailArgs> techEmails) {
            return techEmails(Output.of(techEmails));
        }

        /**
         * @param techEmails Defines the email addresses that will receive alerts about upcoming maintenance updates or warnings about service instability.
         * 
         * @return builder
         * 
         */
        public Builder techEmails(KafkaTechEmailArgs... techEmails) {
            return techEmails(List.of(techEmails));
        }

        /**
         * @param terminationProtection Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
         * 
         * @return builder
         * 
         */
        public Builder terminationProtection(@Nullable Output<Boolean> terminationProtection) {
            $.terminationProtection = terminationProtection;
            return this;
        }

        /**
         * @param terminationProtection Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
         * 
         * @return builder
         * 
         */
        public Builder terminationProtection(Boolean terminationProtection) {
            return terminationProtection(Output.of(terminationProtection));
        }

        public KafkaState build() {
            return $;
        }
    }

}
