// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class KafkaMirrorMakerServiceIntegrationArgs extends com.pulumi.resources.ResourceArgs {

    public static final KafkaMirrorMakerServiceIntegrationArgs Empty = new KafkaMirrorMakerServiceIntegrationArgs();

    /**
     * Type of the service integration
     * 
     */
    @Import(name="integrationType", required=true)
    private Output<String> integrationType;

    /**
     * @return Type of the service integration
     * 
     */
    public Output<String> integrationType() {
        return this.integrationType;
    }

    /**
     * Name of the source service
     * 
     */
    @Import(name="sourceServiceName", required=true)
    private Output<String> sourceServiceName;

    /**
     * @return Name of the source service
     * 
     */
    public Output<String> sourceServiceName() {
        return this.sourceServiceName;
    }

    private KafkaMirrorMakerServiceIntegrationArgs() {}

    private KafkaMirrorMakerServiceIntegrationArgs(KafkaMirrorMakerServiceIntegrationArgs $) {
        this.integrationType = $.integrationType;
        this.sourceServiceName = $.sourceServiceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KafkaMirrorMakerServiceIntegrationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KafkaMirrorMakerServiceIntegrationArgs $;

        public Builder() {
            $ = new KafkaMirrorMakerServiceIntegrationArgs();
        }

        public Builder(KafkaMirrorMakerServiceIntegrationArgs defaults) {
            $ = new KafkaMirrorMakerServiceIntegrationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param integrationType Type of the service integration
         * 
         * @return builder
         * 
         */
        public Builder integrationType(Output<String> integrationType) {
            $.integrationType = integrationType;
            return this;
        }

        /**
         * @param integrationType Type of the service integration
         * 
         * @return builder
         * 
         */
        public Builder integrationType(String integrationType) {
            return integrationType(Output.of(integrationType));
        }

        /**
         * @param sourceServiceName Name of the source service
         * 
         * @return builder
         * 
         */
        public Builder sourceServiceName(Output<String> sourceServiceName) {
            $.sourceServiceName = sourceServiceName;
            return this;
        }

        /**
         * @param sourceServiceName Name of the source service
         * 
         * @return builder
         * 
         */
        public Builder sourceServiceName(String sourceServiceName) {
            return sourceServiceName(Output.of(sourceServiceName));
        }

        public KafkaMirrorMakerServiceIntegrationArgs build() {
            if ($.integrationType == null) {
                throw new MissingRequiredPropertyException("KafkaMirrorMakerServiceIntegrationArgs", "integrationType");
            }
            if ($.sourceServiceName == null) {
                throw new MissingRequiredPropertyException("KafkaMirrorMakerServiceIntegrationArgs", "sourceServiceName");
            }
            return $;
        }
    }

}
