// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class M3DbM3dbUserConfigPrivateAccessArgs extends com.pulumi.resources.ResourceArgs {

    public static final M3DbM3dbUserConfigPrivateAccessArgs Empty = new M3DbM3dbUserConfigPrivateAccessArgs();

    /**
     * Allow clients to connect to m3coordinator with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    @Import(name="m3coordinator")
    private @Nullable Output<Boolean> m3coordinator;

    /**
     * @return Allow clients to connect to m3coordinator with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    public Optional<Output<Boolean>> m3coordinator() {
        return Optional.ofNullable(this.m3coordinator);
    }

    private M3DbM3dbUserConfigPrivateAccessArgs() {}

    private M3DbM3dbUserConfigPrivateAccessArgs(M3DbM3dbUserConfigPrivateAccessArgs $) {
        this.m3coordinator = $.m3coordinator;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(M3DbM3dbUserConfigPrivateAccessArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private M3DbM3dbUserConfigPrivateAccessArgs $;

        public Builder() {
            $ = new M3DbM3dbUserConfigPrivateAccessArgs();
        }

        public Builder(M3DbM3dbUserConfigPrivateAccessArgs defaults) {
            $ = new M3DbM3dbUserConfigPrivateAccessArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param m3coordinator Allow clients to connect to m3coordinator with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
         * 
         * @return builder
         * 
         */
        public Builder m3coordinator(@Nullable Output<Boolean> m3coordinator) {
            $.m3coordinator = m3coordinator;
            return this;
        }

        /**
         * @param m3coordinator Allow clients to connect to m3coordinator with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
         * 
         * @return builder
         * 
         */
        public Builder m3coordinator(Boolean m3coordinator) {
            return m3coordinator(Output.of(m3coordinator));
        }

        public M3DbM3dbUserConfigPrivateAccessArgs build() {
            return $;
        }
    }

}
