// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.aiven.inputs.OrganizationBillingGroupBillingContactEmailArgs;
import com.pulumi.aiven.inputs.OrganizationBillingGroupBillingEmailArgs;
import com.pulumi.aiven.inputs.OrganizationBillingGroupPaymentMethodArgs;
import com.pulumi.aiven.inputs.OrganizationBillingGroupTimeoutsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrganizationBillingGroupState extends com.pulumi.resources.ResourceArgs {

    public static final OrganizationBillingGroupState Empty = new OrganizationBillingGroupState();

    /**
     * Billing address ID. Maximum length: `36`.
     * 
     */
    @Import(name="billingAddressId")
    private @Nullable Output<String> billingAddressId;

    /**
     * @return Billing address ID. Maximum length: `36`.
     * 
     */
    public Optional<Output<String>> billingAddressId() {
        return Optional.ofNullable(this.billingAddressId);
    }

    /**
     * Required property. List of billing contact emails.
     * 
     */
    @Import(name="billingContactEmails")
    private @Nullable Output<List<OrganizationBillingGroupBillingContactEmailArgs>> billingContactEmails;

    /**
     * @return Required property. List of billing contact emails.
     * 
     */
    public Optional<Output<List<OrganizationBillingGroupBillingContactEmailArgs>>> billingContactEmails() {
        return Optional.ofNullable(this.billingContactEmails);
    }

    /**
     * Required property. List of billing contact emails.
     * 
     */
    @Import(name="billingEmails")
    private @Nullable Output<List<OrganizationBillingGroupBillingEmailArgs>> billingEmails;

    /**
     * @return Required property. List of billing contact emails.
     * 
     */
    public Optional<Output<List<OrganizationBillingGroupBillingEmailArgs>>> billingEmails() {
        return Optional.ofNullable(this.billingEmails);
    }

    /**
     * Billing group ID.
     * 
     */
    @Import(name="billingGroupId")
    private @Nullable Output<String> billingGroupId;

    /**
     * @return Billing group ID.
     * 
     */
    public Optional<Output<String>> billingGroupId() {
        return Optional.ofNullable(this.billingGroupId);
    }

    /**
     * Billing Group Name. Maximum length: `128`.
     * 
     */
    @Import(name="billingGroupName")
    private @Nullable Output<String> billingGroupName;

    /**
     * @return Billing Group Name. Maximum length: `128`.
     * 
     */
    public Optional<Output<String>> billingGroupName() {
        return Optional.ofNullable(this.billingGroupName);
    }

    /**
     * Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.
     * 
     */
    @Import(name="currency")
    private @Nullable Output<String> currency;

    /**
     * @return Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.
     * 
     */
    public Optional<Output<String>> currency() {
        return Optional.ofNullable(this.currency);
    }

    /**
     * Extra billing text. Maximum length: `256`.
     * 
     */
    @Import(name="customInvoiceText")
    private @Nullable Output<String> customInvoiceText;

    /**
     * @return Extra billing text. Maximum length: `256`.
     * 
     */
    public Optional<Output<String>> customInvoiceText() {
        return Optional.ofNullable(this.customInvoiceText);
    }

    /**
     * ID of an organization. Maximum length: `36`. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="organizationId")
    private @Nullable Output<String> organizationId;

    /**
     * @return ID of an organization. Maximum length: `36`. Changing this property forces recreation of the resource.
     * 
     */
    public Optional<Output<String>> organizationId() {
        return Optional.ofNullable(this.organizationId);
    }

    /**
     * Required property. Payment method.
     * 
     */
    @Import(name="paymentMethod")
    private @Nullable Output<OrganizationBillingGroupPaymentMethodArgs> paymentMethod;

    /**
     * @return Required property. Payment method.
     * 
     */
    public Optional<Output<OrganizationBillingGroupPaymentMethodArgs>> paymentMethod() {
        return Optional.ofNullable(this.paymentMethod);
    }

    /**
     * Shipping address ID. Maximum length: `36`.
     * 
     */
    @Import(name="shippingAddressId")
    private @Nullable Output<String> shippingAddressId;

    /**
     * @return Shipping address ID. Maximum length: `36`.
     * 
     */
    public Optional<Output<String>> shippingAddressId() {
        return Optional.ofNullable(this.shippingAddressId);
    }

    @Import(name="timeouts")
    private @Nullable Output<OrganizationBillingGroupTimeoutsArgs> timeouts;

    public Optional<Output<OrganizationBillingGroupTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    /**
     * VAT ID.
     * 
     */
    @Import(name="vatId")
    private @Nullable Output<String> vatId;

    /**
     * @return VAT ID.
     * 
     */
    public Optional<Output<String>> vatId() {
        return Optional.ofNullable(this.vatId);
    }

    private OrganizationBillingGroupState() {}

    private OrganizationBillingGroupState(OrganizationBillingGroupState $) {
        this.billingAddressId = $.billingAddressId;
        this.billingContactEmails = $.billingContactEmails;
        this.billingEmails = $.billingEmails;
        this.billingGroupId = $.billingGroupId;
        this.billingGroupName = $.billingGroupName;
        this.currency = $.currency;
        this.customInvoiceText = $.customInvoiceText;
        this.organizationId = $.organizationId;
        this.paymentMethod = $.paymentMethod;
        this.shippingAddressId = $.shippingAddressId;
        this.timeouts = $.timeouts;
        this.vatId = $.vatId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrganizationBillingGroupState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrganizationBillingGroupState $;

        public Builder() {
            $ = new OrganizationBillingGroupState();
        }

        public Builder(OrganizationBillingGroupState defaults) {
            $ = new OrganizationBillingGroupState(Objects.requireNonNull(defaults));
        }

        /**
         * @param billingAddressId Billing address ID. Maximum length: `36`.
         * 
         * @return builder
         * 
         */
        public Builder billingAddressId(@Nullable Output<String> billingAddressId) {
            $.billingAddressId = billingAddressId;
            return this;
        }

        /**
         * @param billingAddressId Billing address ID. Maximum length: `36`.
         * 
         * @return builder
         * 
         */
        public Builder billingAddressId(String billingAddressId) {
            return billingAddressId(Output.of(billingAddressId));
        }

        /**
         * @param billingContactEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingContactEmails(@Nullable Output<List<OrganizationBillingGroupBillingContactEmailArgs>> billingContactEmails) {
            $.billingContactEmails = billingContactEmails;
            return this;
        }

        /**
         * @param billingContactEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingContactEmails(List<OrganizationBillingGroupBillingContactEmailArgs> billingContactEmails) {
            return billingContactEmails(Output.of(billingContactEmails));
        }

        /**
         * @param billingContactEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingContactEmails(OrganizationBillingGroupBillingContactEmailArgs... billingContactEmails) {
            return billingContactEmails(List.of(billingContactEmails));
        }

        /**
         * @param billingEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingEmails(@Nullable Output<List<OrganizationBillingGroupBillingEmailArgs>> billingEmails) {
            $.billingEmails = billingEmails;
            return this;
        }

        /**
         * @param billingEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingEmails(List<OrganizationBillingGroupBillingEmailArgs> billingEmails) {
            return billingEmails(Output.of(billingEmails));
        }

        /**
         * @param billingEmails Required property. List of billing contact emails.
         * 
         * @return builder
         * 
         */
        public Builder billingEmails(OrganizationBillingGroupBillingEmailArgs... billingEmails) {
            return billingEmails(List.of(billingEmails));
        }

        /**
         * @param billingGroupId Billing group ID.
         * 
         * @return builder
         * 
         */
        public Builder billingGroupId(@Nullable Output<String> billingGroupId) {
            $.billingGroupId = billingGroupId;
            return this;
        }

        /**
         * @param billingGroupId Billing group ID.
         * 
         * @return builder
         * 
         */
        public Builder billingGroupId(String billingGroupId) {
            return billingGroupId(Output.of(billingGroupId));
        }

        /**
         * @param billingGroupName Billing Group Name. Maximum length: `128`.
         * 
         * @return builder
         * 
         */
        public Builder billingGroupName(@Nullable Output<String> billingGroupName) {
            $.billingGroupName = billingGroupName;
            return this;
        }

        /**
         * @param billingGroupName Billing Group Name. Maximum length: `128`.
         * 
         * @return builder
         * 
         */
        public Builder billingGroupName(String billingGroupName) {
            return billingGroupName(Output.of(billingGroupName));
        }

        /**
         * @param currency Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.
         * 
         * @return builder
         * 
         */
        public Builder currency(@Nullable Output<String> currency) {
            $.currency = currency;
            return this;
        }

        /**
         * @param currency Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.
         * 
         * @return builder
         * 
         */
        public Builder currency(String currency) {
            return currency(Output.of(currency));
        }

        /**
         * @param customInvoiceText Extra billing text. Maximum length: `256`.
         * 
         * @return builder
         * 
         */
        public Builder customInvoiceText(@Nullable Output<String> customInvoiceText) {
            $.customInvoiceText = customInvoiceText;
            return this;
        }

        /**
         * @param customInvoiceText Extra billing text. Maximum length: `256`.
         * 
         * @return builder
         * 
         */
        public Builder customInvoiceText(String customInvoiceText) {
            return customInvoiceText(Output.of(customInvoiceText));
        }

        /**
         * @param organizationId ID of an organization. Maximum length: `36`. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(@Nullable Output<String> organizationId) {
            $.organizationId = organizationId;
            return this;
        }

        /**
         * @param organizationId ID of an organization. Maximum length: `36`. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder organizationId(String organizationId) {
            return organizationId(Output.of(organizationId));
        }

        /**
         * @param paymentMethod Required property. Payment method.
         * 
         * @return builder
         * 
         */
        public Builder paymentMethod(@Nullable Output<OrganizationBillingGroupPaymentMethodArgs> paymentMethod) {
            $.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * @param paymentMethod Required property. Payment method.
         * 
         * @return builder
         * 
         */
        public Builder paymentMethod(OrganizationBillingGroupPaymentMethodArgs paymentMethod) {
            return paymentMethod(Output.of(paymentMethod));
        }

        /**
         * @param shippingAddressId Shipping address ID. Maximum length: `36`.
         * 
         * @return builder
         * 
         */
        public Builder shippingAddressId(@Nullable Output<String> shippingAddressId) {
            $.shippingAddressId = shippingAddressId;
            return this;
        }

        /**
         * @param shippingAddressId Shipping address ID. Maximum length: `36`.
         * 
         * @return builder
         * 
         */
        public Builder shippingAddressId(String shippingAddressId) {
            return shippingAddressId(Output.of(shippingAddressId));
        }

        public Builder timeouts(@Nullable Output<OrganizationBillingGroupTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(OrganizationBillingGroupTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        /**
         * @param vatId VAT ID.
         * 
         * @return builder
         * 
         */
        public Builder vatId(@Nullable Output<String> vatId) {
            $.vatId = vatId;
            return this;
        }

        /**
         * @param vatId VAT ID.
         * 
         * @return builder
         * 
         */
        public Builder vatId(String vatId) {
            return vatId(Output.of(vatId));
        }

        public OrganizationBillingGroupState build() {
            return $;
        }
    }

}
