// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceIntegrationEndpointRsyslogUserConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceIntegrationEndpointRsyslogUserConfigArgs Empty = new ServiceIntegrationEndpointRsyslogUserConfigArgs();

    @Import(name="ca")
    private @Nullable Output<String> ca;

    public Optional<Output<String>> ca() {
        return Optional.ofNullable(this.ca);
    }

    @Import(name="cert")
    private @Nullable Output<String> cert;

    public Optional<Output<String>> cert() {
        return Optional.ofNullable(this.cert);
    }

    @Import(name="format")
    private @Nullable Output<String> format;

    public Optional<Output<String>> format() {
        return Optional.ofNullable(this.format);
    }

    @Import(name="key")
    private @Nullable Output<String> key;

    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    @Import(name="logline")
    private @Nullable Output<String> logline;

    public Optional<Output<String>> logline() {
        return Optional.ofNullable(this.logline);
    }

    @Import(name="port")
    private @Nullable Output<String> port;

    public Optional<Output<String>> port() {
        return Optional.ofNullable(this.port);
    }

    @Import(name="sd")
    private @Nullable Output<String> sd;

    public Optional<Output<String>> sd() {
        return Optional.ofNullable(this.sd);
    }

    @Import(name="server")
    private @Nullable Output<String> server;

    public Optional<Output<String>> server() {
        return Optional.ofNullable(this.server);
    }

    @Import(name="tls")
    private @Nullable Output<String> tls;

    public Optional<Output<String>> tls() {
        return Optional.ofNullable(this.tls);
    }

    private ServiceIntegrationEndpointRsyslogUserConfigArgs() {}

    private ServiceIntegrationEndpointRsyslogUserConfigArgs(ServiceIntegrationEndpointRsyslogUserConfigArgs $) {
        this.ca = $.ca;
        this.cert = $.cert;
        this.format = $.format;
        this.key = $.key;
        this.logline = $.logline;
        this.port = $.port;
        this.sd = $.sd;
        this.server = $.server;
        this.tls = $.tls;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceIntegrationEndpointRsyslogUserConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceIntegrationEndpointRsyslogUserConfigArgs $;

        public Builder() {
            $ = new ServiceIntegrationEndpointRsyslogUserConfigArgs();
        }

        public Builder(ServiceIntegrationEndpointRsyslogUserConfigArgs defaults) {
            $ = new ServiceIntegrationEndpointRsyslogUserConfigArgs(Objects.requireNonNull(defaults));
        }

        public Builder ca(@Nullable Output<String> ca) {
            $.ca = ca;
            return this;
        }

        public Builder ca(String ca) {
            return ca(Output.of(ca));
        }

        public Builder cert(@Nullable Output<String> cert) {
            $.cert = cert;
            return this;
        }

        public Builder cert(String cert) {
            return cert(Output.of(cert));
        }

        public Builder format(@Nullable Output<String> format) {
            $.format = format;
            return this;
        }

        public Builder format(String format) {
            return format(Output.of(format));
        }

        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public Builder logline(@Nullable Output<String> logline) {
            $.logline = logline;
            return this;
        }

        public Builder logline(String logline) {
            return logline(Output.of(logline));
        }

        public Builder port(@Nullable Output<String> port) {
            $.port = port;
            return this;
        }

        public Builder port(String port) {
            return port(Output.of(port));
        }

        public Builder sd(@Nullable Output<String> sd) {
            $.sd = sd;
            return this;
        }

        public Builder sd(String sd) {
            return sd(Output.of(sd));
        }

        public Builder server(@Nullable Output<String> server) {
            $.server = server;
            return this;
        }

        public Builder server(String server) {
            return server(Output.of(server));
        }

        public Builder tls(@Nullable Output<String> tls) {
            $.tls = tls;
            return this;
        }

        public Builder tls(String tls) {
            return tls(Output.of(tls));
        }

        public ServiceIntegrationEndpointRsyslogUserConfigArgs build() {
            return $;
        }
    }

}
