// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAlloydbomniAlloydbomniUserConfigPglookout {
    /**
     * @return Number of seconds of master unavailability before triggering database failover to standby. Default: `60`.
     * 
     */
    private @Nullable Integer maxFailoverReplicationTimeLag;

    private GetAlloydbomniAlloydbomniUserConfigPglookout() {}
    /**
     * @return Number of seconds of master unavailability before triggering database failover to standby. Default: `60`.
     * 
     */
    public Optional<Integer> maxFailoverReplicationTimeLag() {
        return Optional.ofNullable(this.maxFailoverReplicationTimeLag);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAlloydbomniAlloydbomniUserConfigPglookout defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer maxFailoverReplicationTimeLag;
        public Builder() {}
        public Builder(GetAlloydbomniAlloydbomniUserConfigPglookout defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.maxFailoverReplicationTimeLag = defaults.maxFailoverReplicationTimeLag;
        }

        @CustomType.Setter
        public Builder maxFailoverReplicationTimeLag(@Nullable Integer maxFailoverReplicationTimeLag) {

            this.maxFailoverReplicationTimeLag = maxFailoverReplicationTimeLag;
            return this;
        }
        public GetAlloydbomniAlloydbomniUserConfigPglookout build() {
            final var _resultValue = new GetAlloydbomniAlloydbomniUserConfigPglookout();
            _resultValue.maxFailoverReplicationTimeLag = maxFailoverReplicationTimeLag;
            return _resultValue;
        }
    }
}
