// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetM3DbM3dbUserConfigRulesMappingNamespacesObject {
    private @Nullable String resolution;
    private @Nullable String retention;

    private GetM3DbM3dbUserConfigRulesMappingNamespacesObject() {}
    public Optional<String> resolution() {
        return Optional.ofNullable(this.resolution);
    }
    public Optional<String> retention() {
        return Optional.ofNullable(this.retention);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetM3DbM3dbUserConfigRulesMappingNamespacesObject defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String resolution;
        private @Nullable String retention;
        public Builder() {}
        public Builder(GetM3DbM3dbUserConfigRulesMappingNamespacesObject defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.resolution = defaults.resolution;
    	      this.retention = defaults.retention;
        }

        @CustomType.Setter
        public Builder resolution(@Nullable String resolution) {

            this.resolution = resolution;
            return this;
        }
        @CustomType.Setter
        public Builder retention(@Nullable String retention) {

            this.retention = retention;
            return this;
        }
        public GetM3DbM3dbUserConfigRulesMappingNamespacesObject build() {
            final var _resultValue = new GetM3DbM3dbUserConfigRulesMappingNamespacesObject();
            _resultValue.resolution = resolution;
            _resultValue.retention = retention;
            return _resultValue;
        }
    }
}
