// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold {
    /**
     * @return Debug threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    private @Nullable String debug;
    /**
     * @return Info threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    private @Nullable String info;
    /**
     * @return Trace threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    private @Nullable String trace;
    /**
     * @return Warning threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    private @Nullable String warn;

    private GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold() {}
    /**
     * @return Debug threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    public Optional<String> debug() {
        return Optional.ofNullable(this.debug);
    }
    /**
     * @return Info threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    public Optional<String> info() {
        return Optional.ofNullable(this.info);
    }
    /**
     * @return Trace threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    public Optional<String> trace() {
        return Optional.ofNullable(this.trace);
    }
    /**
     * @return Warning threshold for total request took time. The value should be in the form count and unit, where unit one of (s,m,h,d,nanos,ms,micros) or -1. Default is -1.
     * 
     */
    public Optional<String> warn() {
        return Optional.ofNullable(this.warn);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String debug;
        private @Nullable String info;
        private @Nullable String trace;
        private @Nullable String warn;
        public Builder() {}
        public Builder(GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.debug = defaults.debug;
    	      this.info = defaults.info;
    	      this.trace = defaults.trace;
    	      this.warn = defaults.warn;
        }

        @CustomType.Setter
        public Builder debug(@Nullable String debug) {

            this.debug = debug;
            return this;
        }
        @CustomType.Setter
        public Builder info(@Nullable String info) {

            this.info = info;
            return this;
        }
        @CustomType.Setter
        public Builder trace(@Nullable String trace) {

            this.trace = trace;
            return this;
        }
        @CustomType.Setter
        public Builder warn(@Nullable String warn) {

            this.warn = warn;
            return this;
        }
        public GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold build() {
            final var _resultValue = new GetOpenSearchOpensearchUserConfigOpensearchClusterSearchRequestSlowlogThreshold();
            _resultValue.debug = debug;
            _resultValue.info = info;
            _resultValue.trace = trace;
            _resultValue.warn = warn;
            return _resultValue;
        }
    }
}
