// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetOrganizationalUnitResult {
    /**
     * @return Time of creation
     * 
     */
    private String createTime;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Organizational Unit name
     * 
     */
    private String name;
    /**
     * @return Parent ID
     * 
     */
    private String parentId;
    /**
     * @return Tenant ID
     * 
     */
    private String tenantId;
    /**
     * @return Time of last update
     * 
     */
    private String updateTime;

    private GetOrganizationalUnitResult() {}
    /**
     * @return Time of creation
     * 
     */
    public String createTime() {
        return this.createTime;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Organizational Unit name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Parent ID
     * 
     */
    public String parentId() {
        return this.parentId;
    }
    /**
     * @return Tenant ID
     * 
     */
    public String tenantId() {
        return this.tenantId;
    }
    /**
     * @return Time of last update
     * 
     */
    public String updateTime() {
        return this.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOrganizationalUnitResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createTime;
        private String id;
        private String name;
        private String parentId;
        private String tenantId;
        private String updateTime;
        public Builder() {}
        public Builder(GetOrganizationalUnitResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createTime = defaults.createTime;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.parentId = defaults.parentId;
    	      this.tenantId = defaults.tenantId;
    	      this.updateTime = defaults.updateTime;
        }

        @CustomType.Setter
        public Builder createTime(String createTime) {
            this.createTime = Objects.requireNonNull(createTime);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder parentId(String parentId) {
            this.parentId = Objects.requireNonNull(parentId);
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(String tenantId) {
            this.tenantId = Objects.requireNonNull(tenantId);
            return this;
        }
        @CustomType.Setter
        public Builder updateTime(String updateTime) {
            this.updateTime = Objects.requireNonNull(updateTime);
            return this;
        }
        public GetOrganizationalUnitResult build() {
            final var o = new GetOrganizationalUnitResult();
            o.createTime = createTime;
            o.id = id;
            o.name = name;
            o.parentId = parentId;
            o.tenantId = tenantId;
            o.updateTime = updateTime;
            return o;
        }
    }
}
