// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.aiven.outputs.GetOrganizationUserGroupMemberListMember;
import com.pulumi.aiven.outputs.GetOrganizationUserGroupMemberListTimeouts;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetOrganizationUserGroupMemberListResult {
    /**
     * @return Resource ID composed as: `organization_id/user_group_id`.
     * 
     */
    private String id;
    /**
     * @return User group members.
     * 
     */
    private @Nullable List<GetOrganizationUserGroupMemberListMember> members;
    /**
     * @return ID of an organization.
     * 
     */
    private String organizationId;
    private @Nullable GetOrganizationUserGroupMemberListTimeouts timeouts;
    /**
     * @return ID of the user group.
     * 
     */
    private String userGroupId;

    private GetOrganizationUserGroupMemberListResult() {}
    /**
     * @return Resource ID composed as: `organization_id/user_group_id`.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return User group members.
     * 
     */
    public List<GetOrganizationUserGroupMemberListMember> members() {
        return this.members == null ? List.of() : this.members;
    }
    /**
     * @return ID of an organization.
     * 
     */
    public String organizationId() {
        return this.organizationId;
    }
    public Optional<GetOrganizationUserGroupMemberListTimeouts> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }
    /**
     * @return ID of the user group.
     * 
     */
    public String userGroupId() {
        return this.userGroupId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOrganizationUserGroupMemberListResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private @Nullable List<GetOrganizationUserGroupMemberListMember> members;
        private String organizationId;
        private @Nullable GetOrganizationUserGroupMemberListTimeouts timeouts;
        private String userGroupId;
        public Builder() {}
        public Builder(GetOrganizationUserGroupMemberListResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.members = defaults.members;
    	      this.organizationId = defaults.organizationId;
    	      this.timeouts = defaults.timeouts;
    	      this.userGroupId = defaults.userGroupId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetOrganizationUserGroupMemberListResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder members(@Nullable List<GetOrganizationUserGroupMemberListMember> members) {

            this.members = members;
            return this;
        }
        public Builder members(GetOrganizationUserGroupMemberListMember... members) {
            return members(List.of(members));
        }
        @CustomType.Setter
        public Builder organizationId(String organizationId) {
            if (organizationId == null) {
              throw new MissingRequiredPropertyException("GetOrganizationUserGroupMemberListResult", "organizationId");
            }
            this.organizationId = organizationId;
            return this;
        }
        @CustomType.Setter
        public Builder timeouts(@Nullable GetOrganizationUserGroupMemberListTimeouts timeouts) {

            this.timeouts = timeouts;
            return this;
        }
        @CustomType.Setter
        public Builder userGroupId(String userGroupId) {
            if (userGroupId == null) {
              throw new MissingRequiredPropertyException("GetOrganizationUserGroupMemberListResult", "userGroupId");
            }
            this.userGroupId = userGroupId;
            return this;
        }
        public GetOrganizationUserGroupMemberListResult build() {
            final var _resultValue = new GetOrganizationUserGroupMemberListResult();
            _resultValue.id = id;
            _resultValue.members = members;
            _resultValue.organizationId = organizationId;
            _resultValue.timeouts = timeouts;
            _resultValue.userGroupId = userGroupId;
            return _resultValue;
        }
    }
}
