// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetOrganizationResult {
    /**
     * @return Timestamp of the creation of the organization.
     * 
     */
    private String createTime;
    /**
     * @return Identifier of the organization.
     * 
     */
    private @Nullable String id;
    /**
     * @return Name of the organization.
     * 
     */
    private @Nullable String name;
    /**
     * @return Tenant identifier of the organization.
     * 
     */
    private String tenantId;
    /**
     * @return Timestamp of the last update of the organization.
     * 
     */
    private String updateTime;

    private GetOrganizationResult() {}
    /**
     * @return Timestamp of the creation of the organization.
     * 
     */
    public String createTime() {
        return this.createTime;
    }
    /**
     * @return Identifier of the organization.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return Name of the organization.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Tenant identifier of the organization.
     * 
     */
    public String tenantId() {
        return this.tenantId;
    }
    /**
     * @return Timestamp of the last update of the organization.
     * 
     */
    public String updateTime() {
        return this.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOrganizationResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createTime;
        private @Nullable String id;
        private @Nullable String name;
        private String tenantId;
        private String updateTime;
        public Builder() {}
        public Builder(GetOrganizationResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createTime = defaults.createTime;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.tenantId = defaults.tenantId;
    	      this.updateTime = defaults.updateTime;
        }

        @CustomType.Setter
        public Builder createTime(String createTime) {
            if (createTime == null) {
              throw new MissingRequiredPropertyException("GetOrganizationResult", "createTime");
            }
            this.createTime = createTime;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(String tenantId) {
            if (tenantId == null) {
              throw new MissingRequiredPropertyException("GetOrganizationResult", "tenantId");
            }
            this.tenantId = tenantId;
            return this;
        }
        @CustomType.Setter
        public Builder updateTime(String updateTime) {
            if (updateTime == null) {
              throw new MissingRequiredPropertyException("GetOrganizationResult", "updateTime");
            }
            this.updateTime = updateTime;
            return this;
        }
        public GetOrganizationResult build() {
            final var _resultValue = new GetOrganizationResult();
            _resultValue.createTime = createTime;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.tenantId = tenantId;
            _resultValue.updateTime = updateTime;
            return _resultValue;
        }
    }
}
