// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetServiceIntegrationMirrormakerUserConfig {
    private @Nullable String mirrormakerWhitelist;

    private GetServiceIntegrationMirrormakerUserConfig() {}
    public Optional<String> mirrormakerWhitelist() {
        return Optional.ofNullable(this.mirrormakerWhitelist);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServiceIntegrationMirrormakerUserConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String mirrormakerWhitelist;
        public Builder() {}
        public Builder(GetServiceIntegrationMirrormakerUserConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.mirrormakerWhitelist = defaults.mirrormakerWhitelist;
        }

        @CustomType.Setter
        public Builder mirrormakerWhitelist(@Nullable String mirrormakerWhitelist) {
            this.mirrormakerWhitelist = mirrormakerWhitelist;
            return this;
        }
        public GetServiceIntegrationMirrormakerUserConfig build() {
            final var o = new GetServiceIntegrationMirrormakerUserConfig();
            o.mirrormakerWhitelist = mirrormakerWhitelist;
            return o;
        }
    }
}
