// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RedisRedisUserConfigPrivateAccess {
    /**
     * @return Allow clients to connect to prometheus with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    private @Nullable Boolean prometheus;
    /**
     * @return Allow clients to connect to redis with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    private @Nullable Boolean redis;

    private RedisRedisUserConfigPrivateAccess() {}
    /**
     * @return Allow clients to connect to prometheus with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    public Optional<Boolean> prometheus() {
        return Optional.ofNullable(this.prometheus);
    }
    /**
     * @return Allow clients to connect to redis with a DNS name that always resolves to the service&#39;s private IP addresses. Only available in certain network locations.
     * 
     */
    public Optional<Boolean> redis() {
        return Optional.ofNullable(this.redis);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RedisRedisUserConfigPrivateAccess defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean prometheus;
        private @Nullable Boolean redis;
        public Builder() {}
        public Builder(RedisRedisUserConfigPrivateAccess defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.prometheus = defaults.prometheus;
    	      this.redis = defaults.redis;
        }

        @CustomType.Setter
        public Builder prometheus(@Nullable Boolean prometheus) {

            this.prometheus = prometheus;
            return this;
        }
        @CustomType.Setter
        public Builder redis(@Nullable Boolean redis) {

            this.redis = redis;
            return this;
        }
        public RedisRedisUserConfigPrivateAccess build() {
            final var _resultValue = new RedisRedisUserConfigPrivateAccess();
            _resultValue.prometheus = prometheus;
            _resultValue.redis = redis;
            return _resultValue;
        }
    }
}
