// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Outputs
{

    [OutputType]
    public sealed class GetAlloydbomniAlloydbomniUserConfigPgbouncerResult
    {
        /// <summary>
        /// If the automatically created database pools have been unused this many seconds, they are freed. If 0 then timeout is disabled. (seconds). Default: `3600`.
        /// </summary>
        public readonly int? AutodbIdleTimeout;
        /// <summary>
        /// Do not allow more than this many server connections per database (regardless of user). Setting it to 0 means unlimited. Example: `0`.
        /// </summary>
        public readonly int? AutodbMaxDbConnections;
        /// <summary>
        /// Enum: `session`, `statement`, `transaction`. PGBouncer pool mode. Default: `transaction`.
        /// </summary>
        public readonly string? AutodbPoolMode;
        /// <summary>
        /// If non-zero then create automatically a pool of that size per user when a pool doesn't exist. Default: `0`.
        /// </summary>
        public readonly int? AutodbPoolSize;
        /// <summary>
        /// List of parameters to ignore when given in startup packet.
        /// </summary>
        public readonly ImmutableArray<string> IgnoreStartupParameters;
        /// <summary>
        /// PgBouncer tracks protocol-level named prepared statements related commands sent by the client in transaction and statement pooling modes when max_prepared_statements is set to a non-zero value. Setting it to 0 disables prepared statements. max_prepared_statements defaults to 100, and its maximum is 3000. Default: `100`.
        /// </summary>
        public readonly int? MaxPreparedStatements;
        /// <summary>
        /// Add more server connections to pool if below this number. Improves behavior when usual load comes suddenly back after period of total inactivity. The value is effectively capped at the pool size. Default: `0`.
        /// </summary>
        public readonly int? MinPoolSize;
        /// <summary>
        /// If a server connection has been idle more than this many seconds it will be dropped. If 0 then timeout is disabled. (seconds). Default: `600`.
        /// </summary>
        public readonly int? ServerIdleTimeout;
        /// <summary>
        /// The pooler will close an unused server connection that has been connected longer than this. (seconds). Default: `3600`.
        /// </summary>
        public readonly int? ServerLifetime;
        /// <summary>
        /// Run server_reset_query (DISCARD ALL) in all pooling modes. Default: `false`.
        /// </summary>
        public readonly bool? ServerResetQueryAlways;

        [OutputConstructor]
        private GetAlloydbomniAlloydbomniUserConfigPgbouncerResult(
            int? autodbIdleTimeout,

            int? autodbMaxDbConnections,

            string? autodbPoolMode,

            int? autodbPoolSize,

            ImmutableArray<string> ignoreStartupParameters,

            int? maxPreparedStatements,

            int? minPoolSize,

            int? serverIdleTimeout,

            int? serverLifetime,

            bool? serverResetQueryAlways)
        {
            AutodbIdleTimeout = autodbIdleTimeout;
            AutodbMaxDbConnections = autodbMaxDbConnections;
            AutodbPoolMode = autodbPoolMode;
            AutodbPoolSize = autodbPoolSize;
            IgnoreStartupParameters = ignoreStartupParameters;
            MaxPreparedStatements = maxPreparedStatements;
            MinPoolSize = minPoolSize;
            ServerIdleTimeout = serverIdleTimeout;
            ServerLifetime = serverLifetime;
            ServerResetQueryAlways = serverResetQueryAlways;
        }
    }
}
