// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Outputs
{

    [OutputType]
    public sealed class GetServiceIntegrationClickhouseKafkaUserConfigTableColumnResult
    {
        /// <summary>
        /// Column name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Column type.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetServiceIntegrationClickhouseKafkaUserConfigTableColumnResult(
            string name,

            string type)
        {
            Name = name;
            Type = type;
        }
    }
}
