// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aiven

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets information about an Azure VPC peering connection.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := aiven.GetAzureOrgVpcPeeringConnection(ctx, &aiven.LookupAzureOrgVpcPeeringConnectionArgs{
//				OrganizationId:      "org1a23f456789",
//				OrganizationVpcId:   "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
//				AzureSubscriptionId: "12345678-1234-1234-1234-123456789012",
//				VnetName:            "my-vnet",
//				PeerResourceGroup:   "my-resource-group",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupAzureOrgVpcPeeringConnection(ctx *pulumi.Context, args *LookupAzureOrgVpcPeeringConnectionArgs, opts ...pulumi.InvokeOption) (*LookupAzureOrgVpcPeeringConnectionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAzureOrgVpcPeeringConnectionResult
	err := ctx.Invoke("aiven:index/getAzureOrgVpcPeeringConnection:getAzureOrgVpcPeeringConnection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAzureOrgVpcPeeringConnection.
type LookupAzureOrgVpcPeeringConnectionArgs struct {
	// The ID of the Azure subscription in UUID4 format.
	AzureSubscriptionId string `pulumi:"azureSubscriptionId"`
	// ID of an organization.
	OrganizationId string `pulumi:"organizationId"`
	// Organization VPC ID.
	OrganizationVpcId string `pulumi:"organizationVpcId"`
	// The name of the Azure resource group associated with the VNet.
	PeerResourceGroup string                                   `pulumi:"peerResourceGroup"`
	Timeouts          *GetAzureOrgVpcPeeringConnectionTimeouts `pulumi:"timeouts"`
	// The name of the Azure VNet.
	VnetName string `pulumi:"vnetName"`
}

// A collection of values returned by getAzureOrgVpcPeeringConnection.
type LookupAzureOrgVpcPeeringConnectionResult struct {
	// The ID of the Azure subscription in UUID4 format.
	AzureSubscriptionId string `pulumi:"azureSubscriptionId"`
	// Resource ID composed as: `organization_id/organization_vpc_id/azure_subscription_id/vnet_name/peer_resource_group`.
	Id string `pulumi:"id"`
	// ID of an organization.
	OrganizationId string `pulumi:"organizationId"`
	// Organization VPC ID.
	OrganizationVpcId string `pulumi:"organizationVpcId"`
	// The ID of the Azure app that is allowed to create a peering to the Azure Virtual Network (VNet) in UUID4 format.
	PeerAzureAppId string `pulumi:"peerAzureAppId"`
	// The Azure tenant ID in UUID4 format.
	PeerAzureTenantId string `pulumi:"peerAzureTenantId"`
	// The name of the Azure resource group associated with the VNet.
	PeerResourceGroup string `pulumi:"peerResourceGroup"`
	// Organization peering connection ID.
	PeeringConnectionId string `pulumi:"peeringConnectionId"`
	// State of the peering connection. The possible values are `ACTIVE`, `APPROVED`, `APPROVED_PEER_REQUESTED`, `DELETED`, `DELETED_BY_PEER`, `DELETING`, `ERROR`, `INVALID_SPECIFICATION`, `PENDING_PEER` and `REJECTED_BY_PEER`.
	State    string                                   `pulumi:"state"`
	Timeouts *GetAzureOrgVpcPeeringConnectionTimeouts `pulumi:"timeouts"`
	// The name of the Azure VNet.
	VnetName string `pulumi:"vnetName"`
}

func LookupAzureOrgVpcPeeringConnectionOutput(ctx *pulumi.Context, args LookupAzureOrgVpcPeeringConnectionOutputArgs, opts ...pulumi.InvokeOption) LookupAzureOrgVpcPeeringConnectionResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("aiven:index/getAzureOrgVpcPeeringConnection:getAzureOrgVpcPeeringConnection", args, LookupAzureOrgVpcPeeringConnectionResultOutput{}, options).(LookupAzureOrgVpcPeeringConnectionResultOutput)
}

// A collection of arguments for invoking getAzureOrgVpcPeeringConnection.
type LookupAzureOrgVpcPeeringConnectionOutputArgs struct {
	// The ID of the Azure subscription in UUID4 format.
	AzureSubscriptionId pulumi.StringInput `pulumi:"azureSubscriptionId"`
	// ID of an organization.
	OrganizationId pulumi.StringInput `pulumi:"organizationId"`
	// Organization VPC ID.
	OrganizationVpcId pulumi.StringInput `pulumi:"organizationVpcId"`
	// The name of the Azure resource group associated with the VNet.
	PeerResourceGroup pulumi.StringInput                              `pulumi:"peerResourceGroup"`
	Timeouts          GetAzureOrgVpcPeeringConnectionTimeoutsPtrInput `pulumi:"timeouts"`
	// The name of the Azure VNet.
	VnetName pulumi.StringInput `pulumi:"vnetName"`
}

func (LookupAzureOrgVpcPeeringConnectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAzureOrgVpcPeeringConnectionArgs)(nil)).Elem()
}

// A collection of values returned by getAzureOrgVpcPeeringConnection.
type LookupAzureOrgVpcPeeringConnectionResultOutput struct{ *pulumi.OutputState }

func (LookupAzureOrgVpcPeeringConnectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAzureOrgVpcPeeringConnectionResult)(nil)).Elem()
}

func (o LookupAzureOrgVpcPeeringConnectionResultOutput) ToLookupAzureOrgVpcPeeringConnectionResultOutput() LookupAzureOrgVpcPeeringConnectionResultOutput {
	return o
}

func (o LookupAzureOrgVpcPeeringConnectionResultOutput) ToLookupAzureOrgVpcPeeringConnectionResultOutputWithContext(ctx context.Context) LookupAzureOrgVpcPeeringConnectionResultOutput {
	return o
}

// The ID of the Azure subscription in UUID4 format.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) AzureSubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.AzureSubscriptionId }).(pulumi.StringOutput)
}

// Resource ID composed as: `organization_id/organization_vpc_id/azure_subscription_id/vnet_name/peer_resource_group`.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.Id }).(pulumi.StringOutput)
}

// ID of an organization.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// Organization VPC ID.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) OrganizationVpcId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.OrganizationVpcId }).(pulumi.StringOutput)
}

// The ID of the Azure app that is allowed to create a peering to the Azure Virtual Network (VNet) in UUID4 format.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) PeerAzureAppId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.PeerAzureAppId }).(pulumi.StringOutput)
}

// The Azure tenant ID in UUID4 format.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) PeerAzureTenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.PeerAzureTenantId }).(pulumi.StringOutput)
}

// The name of the Azure resource group associated with the VNet.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) PeerResourceGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.PeerResourceGroup }).(pulumi.StringOutput)
}

// Organization peering connection ID.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) PeeringConnectionId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.PeeringConnectionId }).(pulumi.StringOutput)
}

// State of the peering connection. The possible values are `ACTIVE`, `APPROVED`, `APPROVED_PEER_REQUESTED`, `DELETED`, `DELETED_BY_PEER`, `DELETING`, `ERROR`, `INVALID_SPECIFICATION`, `PENDING_PEER` and `REJECTED_BY_PEER`.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupAzureOrgVpcPeeringConnectionResultOutput) Timeouts() GetAzureOrgVpcPeeringConnectionTimeoutsPtrOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) *GetAzureOrgVpcPeeringConnectionTimeouts {
		return v.Timeouts
	}).(GetAzureOrgVpcPeeringConnectionTimeoutsPtrOutput)
}

// The name of the Azure VNet.
func (o LookupAzureOrgVpcPeeringConnectionResultOutput) VnetName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAzureOrgVpcPeeringConnectionResult) string { return v.VnetName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAzureOrgVpcPeeringConnectionResultOutput{})
}
