// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package aiven

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupElasticSearchAclRule(ctx *pulumi.Context, args *LookupElasticSearchAclRuleArgs, opts ...pulumi.InvokeOption) (*LookupElasticSearchAclRuleResult, error) {
	var rv LookupElasticSearchAclRuleResult
	err := ctx.Invoke("aiven:index/getElasticSearchAclRule:getElasticSearchAclRule", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getElasticSearchAclRule.
type LookupElasticSearchAclRuleArgs struct {
	Index       string `pulumi:"index"`
	Permission  string `pulumi:"permission"`
	Project     string `pulumi:"project"`
	ServiceName string `pulumi:"serviceName"`
	Username    string `pulumi:"username"`
}

// A collection of values returned by getElasticSearchAclRule.
type LookupElasticSearchAclRuleResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Index       string `pulumi:"index"`
	Permission  string `pulumi:"permission"`
	Project     string `pulumi:"project"`
	ServiceName string `pulumi:"serviceName"`
	Username    string `pulumi:"username"`
}
