// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aiven

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets information about an organizational unit.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := aiven.LookupOrganizationalUnit(ctx, &aiven.LookupOrganizationalUnitArgs{
//				Name: pulumi.StringRef("Example organizational unit"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupOrganizationalUnit(ctx *pulumi.Context, args *LookupOrganizationalUnitArgs, opts ...pulumi.InvokeOption) (*LookupOrganizationalUnitResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrganizationalUnitResult
	err := ctx.Invoke("aiven:index/getOrganizationalUnit:getOrganizationalUnit", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationalUnit.
type LookupOrganizationalUnitArgs struct {
	// The ID of this resource. Exactly one of the fields must be specified: `id` or `name`.
	Id *string `pulumi:"id"`
	// The name of the organizational unit. Exactly one of the fields must be specified: `id` or `name`.
	Name     *string                        `pulumi:"name"`
	Timeouts *GetOrganizationalUnitTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getOrganizationalUnit.
type LookupOrganizationalUnitResult struct {
	// Timestamp in ISO 8601 format, always in UTC.
	CreateTime string `pulumi:"createTime"`
	// The ID of this resource. Exactly one of the fields must be specified: `id` or `name`.
	Id string `pulumi:"id"`
	// The name of the organizational unit. Exactly one of the fields must be specified: `id` or `name`.
	Name string `pulumi:"name"`
	// The ID of the organization that the unit is created in.
	ParentId string `pulumi:"parentId"`
	// Tenant identifier.
	TenantId string                         `pulumi:"tenantId"`
	Timeouts *GetOrganizationalUnitTimeouts `pulumi:"timeouts"`
	// Timestamp in ISO 8601 format, always in UTC.
	UpdateTime string `pulumi:"updateTime"`
}

func LookupOrganizationalUnitOutput(ctx *pulumi.Context, args LookupOrganizationalUnitOutputArgs, opts ...pulumi.InvokeOption) LookupOrganizationalUnitResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrganizationalUnitResultOutput, error) {
			args := v.(LookupOrganizationalUnitArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("aiven:index/getOrganizationalUnit:getOrganizationalUnit", args, LookupOrganizationalUnitResultOutput{}, options).(LookupOrganizationalUnitResultOutput), nil
		}).(LookupOrganizationalUnitResultOutput)
}

// A collection of arguments for invoking getOrganizationalUnit.
type LookupOrganizationalUnitOutputArgs struct {
	// The ID of this resource. Exactly one of the fields must be specified: `id` or `name`.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the organizational unit. Exactly one of the fields must be specified: `id` or `name`.
	Name     pulumi.StringPtrInput                 `pulumi:"name"`
	Timeouts GetOrganizationalUnitTimeoutsPtrInput `pulumi:"timeouts"`
}

func (LookupOrganizationalUnitOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationalUnitArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationalUnit.
type LookupOrganizationalUnitResultOutput struct{ *pulumi.OutputState }

func (LookupOrganizationalUnitResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationalUnitResult)(nil)).Elem()
}

func (o LookupOrganizationalUnitResultOutput) ToLookupOrganizationalUnitResultOutput() LookupOrganizationalUnitResultOutput {
	return o
}

func (o LookupOrganizationalUnitResultOutput) ToLookupOrganizationalUnitResultOutputWithContext(ctx context.Context) LookupOrganizationalUnitResultOutput {
	return o
}

// Timestamp in ISO 8601 format, always in UTC.
func (o LookupOrganizationalUnitResultOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.CreateTime }).(pulumi.StringOutput)
}

// The ID of this resource. Exactly one of the fields must be specified: `id` or `name`.
func (o LookupOrganizationalUnitResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the organizational unit. Exactly one of the fields must be specified: `id` or `name`.
func (o LookupOrganizationalUnitResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.Name }).(pulumi.StringOutput)
}

// The ID of the organization that the unit is created in.
func (o LookupOrganizationalUnitResultOutput) ParentId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.ParentId }).(pulumi.StringOutput)
}

// Tenant identifier.
func (o LookupOrganizationalUnitResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.TenantId }).(pulumi.StringOutput)
}

func (o LookupOrganizationalUnitResultOutput) Timeouts() GetOrganizationalUnitTimeoutsPtrOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) *GetOrganizationalUnitTimeouts { return v.Timeouts }).(GetOrganizationalUnitTimeoutsPtrOutput)
}

// Timestamp in ISO 8601 format, always in UTC.
func (o LookupOrganizationalUnitResultOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationalUnitResult) string { return v.UpdateTime }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrganizationalUnitResultOutput{})
}
