// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package aiven

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Service Integration Endpoint Data Source
//
// The Service Integration Endpoint data source provides information about the existing
// Aiven Service Integration Endpoint.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-aiven/sdk/v4/go/aiven"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := aiven.LookupServiceIntegrationEndpoint(ctx, &aiven.LookupServiceIntegrationEndpointArgs{
// 			Project:      aiven_project.Myproject.Project,
// 			EndpointName: "<ENDPOINT_NAME>",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupServiceIntegrationEndpoint(ctx *pulumi.Context, args *LookupServiceIntegrationEndpointArgs, opts ...pulumi.InvokeOption) (*LookupServiceIntegrationEndpointResult, error) {
	var rv LookupServiceIntegrationEndpointResult
	err := ctx.Invoke("aiven:index/getServiceIntegrationEndpoint:getServiceIntegrationEndpoint", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServiceIntegrationEndpoint.
type LookupServiceIntegrationEndpointArgs struct {
	DatadogUserConfig *GetServiceIntegrationEndpointDatadogUserConfig `pulumi:"datadogUserConfig"`
	EndpointConfig    map[string]string                               `pulumi:"endpointConfig"`
	// is the name of the endpoint. This value has no effect beyond being used
	// to identify different integration endpoints.
	EndpointName string `pulumi:"endpointName"`
	// is the type of the external service this endpoint is associated with.
	// By the time of writing the only available option is `datadog`.
	EndpointType                           *string                                                              `pulumi:"endpointType"`
	ExternalAwsCloudwatchLogsUserConfig    *GetServiceIntegrationEndpointExternalAwsCloudwatchLogsUserConfig    `pulumi:"externalAwsCloudwatchLogsUserConfig"`
	ExternalAwsCloudwatchMetricsUserConfig *GetServiceIntegrationEndpointExternalAwsCloudwatchMetricsUserConfig `pulumi:"externalAwsCloudwatchMetricsUserConfig"`
	ExternalElasticsearchLogsUserConfig    *GetServiceIntegrationEndpointExternalElasticsearchLogsUserConfig    `pulumi:"externalElasticsearchLogsUserConfig"`
	ExternalGoogleCloudLoggingUserConfig   *GetServiceIntegrationEndpointExternalGoogleCloudLoggingUserConfig   `pulumi:"externalGoogleCloudLoggingUserConfig"`
	ExternalKafkaUserConfig                *GetServiceIntegrationEndpointExternalKafkaUserConfig                `pulumi:"externalKafkaUserConfig"`
	ExternalSchemaRegistryUserConfig       *GetServiceIntegrationEndpointExternalSchemaRegistryUserConfig       `pulumi:"externalSchemaRegistryUserConfig"`
	JolokiaUserConfig                      *GetServiceIntegrationEndpointJolokiaUserConfig                      `pulumi:"jolokiaUserConfig"`
	// defines the project the endpoint is associated with.
	Project              string                                             `pulumi:"project"`
	PrometheusUserConfig *GetServiceIntegrationEndpointPrometheusUserConfig `pulumi:"prometheusUserConfig"`
	RsyslogUserConfig    *GetServiceIntegrationEndpointRsyslogUserConfig    `pulumi:"rsyslogUserConfig"`
	SignalfxUserConfig   *GetServiceIntegrationEndpointSignalfxUserConfig   `pulumi:"signalfxUserConfig"`
}

// A collection of values returned by getServiceIntegrationEndpoint.
type LookupServiceIntegrationEndpointResult struct {
	DatadogUserConfig *GetServiceIntegrationEndpointDatadogUserConfig `pulumi:"datadogUserConfig"`
	EndpointConfig    map[string]string                               `pulumi:"endpointConfig"`
	EndpointName      string                                          `pulumi:"endpointName"`
	// is the type of the external service this endpoint is associated with.
	// By the time of writing the only available option is `datadog`.
	EndpointType                           *string                                                              `pulumi:"endpointType"`
	ExternalAwsCloudwatchLogsUserConfig    *GetServiceIntegrationEndpointExternalAwsCloudwatchLogsUserConfig    `pulumi:"externalAwsCloudwatchLogsUserConfig"`
	ExternalAwsCloudwatchMetricsUserConfig *GetServiceIntegrationEndpointExternalAwsCloudwatchMetricsUserConfig `pulumi:"externalAwsCloudwatchMetricsUserConfig"`
	ExternalElasticsearchLogsUserConfig    *GetServiceIntegrationEndpointExternalElasticsearchLogsUserConfig    `pulumi:"externalElasticsearchLogsUserConfig"`
	ExternalGoogleCloudLoggingUserConfig   *GetServiceIntegrationEndpointExternalGoogleCloudLoggingUserConfig   `pulumi:"externalGoogleCloudLoggingUserConfig"`
	ExternalKafkaUserConfig                *GetServiceIntegrationEndpointExternalKafkaUserConfig                `pulumi:"externalKafkaUserConfig"`
	ExternalSchemaRegistryUserConfig       *GetServiceIntegrationEndpointExternalSchemaRegistryUserConfig       `pulumi:"externalSchemaRegistryUserConfig"`
	// The provider-assigned unique ID for this managed resource.
	Id                   string                                             `pulumi:"id"`
	JolokiaUserConfig    *GetServiceIntegrationEndpointJolokiaUserConfig    `pulumi:"jolokiaUserConfig"`
	Project              string                                             `pulumi:"project"`
	PrometheusUserConfig *GetServiceIntegrationEndpointPrometheusUserConfig `pulumi:"prometheusUserConfig"`
	RsyslogUserConfig    *GetServiceIntegrationEndpointRsyslogUserConfig    `pulumi:"rsyslogUserConfig"`
	SignalfxUserConfig   *GetServiceIntegrationEndpointSignalfxUserConfig   `pulumi:"signalfxUserConfig"`
}
