// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aiven

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates and manages an [Aiven for Metrics®](https://aiven.io/docs/products/metrics/concepts/metrics-overview) service.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-aiven/sdk/v6/go/aiven"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := aiven.NewThanos(ctx, "example_thanos", &aiven.ThanosArgs{
//				Project:     pulumi.Any(exampleProject.Project),
//				Plan:        pulumi.String("startup-4"),
//				CloudName:   pulumi.String("google-europe-west1"),
//				ServiceName: pulumi.String("example-thanos-service"),
//				ThanosUserConfig: &aiven.ThanosThanosUserConfigArgs{
//					Compactor: &aiven.ThanosThanosUserConfigCompactorArgs{
//						RetentionDays: pulumi.Int(30),
//					},
//					ObjectStorageUsageAlertThresholdGb: pulumi.Int(10),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import aiven:index/thanos:Thanos example_thanos PROJECT/SERVICE_NAME
// ```
type Thanos struct {
	pulumi.CustomResourceState

	// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
	AdditionalDiskSpace pulumi.StringOutput `pulumi:"additionalDiskSpace"`
	// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
	CloudName pulumi.StringPtrOutput `pulumi:"cloudName"`
	// Service component information objects
	Components ThanosComponentArrayOutput `pulumi:"components"`
	// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	//
	// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	DiskSpace pulumi.StringPtrOutput `pulumi:"diskSpace"`
	// The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
	DiskSpaceCap pulumi.StringOutput `pulumi:"diskSpaceCap"`
	// The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `diskSpace`
	DiskSpaceDefault pulumi.StringOutput `pulumi:"diskSpaceDefault"`
	// The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `diskSpace` needs to increment from `diskSpaceDefault` by increments of this size.
	DiskSpaceStep pulumi.StringOutput `pulumi:"diskSpaceStep"`
	// The disk space that the service is currently using. This is the sum of `diskSpace` and `additionalDiskSpace` in human-readable format (for example: `90GiB`).
	DiskSpaceUsed pulumi.StringOutput `pulumi:"diskSpaceUsed"`
	// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
	MaintenanceWindowDow pulumi.StringPtrOutput `pulumi:"maintenanceWindowDow"`
	// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
	MaintenanceWindowTime pulumi.StringPtrOutput `pulumi:"maintenanceWindowTime"`
	// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
	Plan pulumi.StringOutput `pulumi:"plan"`
	// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
	Project pulumi.StringOutput `pulumi:"project"`
	// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
	ProjectVpcId pulumi.StringPtrOutput `pulumi:"projectVpcId"`
	// The hostname of the service.
	ServiceHost pulumi.StringOutput `pulumi:"serviceHost"`
	// Service integrations to specify when creating a service. Not applied after initial service creation
	ServiceIntegrations ThanosServiceIntegrationArrayOutput `pulumi:"serviceIntegrations"`
	// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
	// Password used for connecting to the service, if applicable
	ServicePassword pulumi.StringOutput `pulumi:"servicePassword"`
	// The port of the service
	ServicePort pulumi.IntOutput `pulumi:"servicePort"`
	// Aiven internal service type code
	ServiceType pulumi.StringOutput `pulumi:"serviceType"`
	// URI for connecting to the service. Service specific info is under "kafka", "pg", etc.
	ServiceUri pulumi.StringOutput `pulumi:"serviceUri"`
	// Username used for connecting to the service, if applicable
	ServiceUsername pulumi.StringOutput `pulumi:"serviceUsername"`
	State           pulumi.StringOutput `pulumi:"state"`
	// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
	StaticIps pulumi.StringArrayOutput `pulumi:"staticIps"`
	// Tags are key-value pairs that allow you to categorize services.
	Tags ThanosTagArrayOutput `pulumi:"tags"`
	// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
	TechEmails ThanosTechEmailArrayOutput `pulumi:"techEmails"`
	// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
	TerminationProtection pulumi.BoolPtrOutput `pulumi:"terminationProtection"`
	// Thanos server connection details.
	Thanos ThanosThanosOutput `pulumi:"thanos"`
	// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
	ThanosUserConfig ThanosThanosUserConfigPtrOutput `pulumi:"thanosUserConfig"`
}

// NewThanos registers a new resource with the given unique name, arguments, and options.
func NewThanos(ctx *pulumi.Context,
	name string, args *ThanosArgs, opts ...pulumi.ResourceOption) (*Thanos, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	if args.Thanos != nil {
		args.Thanos = pulumi.ToSecret(args.Thanos).(ThanosThanosPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"servicePassword",
		"serviceUri",
		"thanos",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Thanos
	err := ctx.RegisterResource("aiven:index/thanos:Thanos", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetThanos gets an existing Thanos resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetThanos(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ThanosState, opts ...pulumi.ResourceOption) (*Thanos, error) {
	var resource Thanos
	err := ctx.ReadResource("aiven:index/thanos:Thanos", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Thanos resources.
type thanosState struct {
	// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
	AdditionalDiskSpace *string `pulumi:"additionalDiskSpace"`
	// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
	CloudName *string `pulumi:"cloudName"`
	// Service component information objects
	Components []ThanosComponent `pulumi:"components"`
	// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	//
	// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	DiskSpace *string `pulumi:"diskSpace"`
	// The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
	DiskSpaceCap *string `pulumi:"diskSpaceCap"`
	// The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `diskSpace`
	DiskSpaceDefault *string `pulumi:"diskSpaceDefault"`
	// The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `diskSpace` needs to increment from `diskSpaceDefault` by increments of this size.
	DiskSpaceStep *string `pulumi:"diskSpaceStep"`
	// The disk space that the service is currently using. This is the sum of `diskSpace` and `additionalDiskSpace` in human-readable format (for example: `90GiB`).
	DiskSpaceUsed *string `pulumi:"diskSpaceUsed"`
	// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
	MaintenanceWindowDow *string `pulumi:"maintenanceWindowDow"`
	// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
	MaintenanceWindowTime *string `pulumi:"maintenanceWindowTime"`
	// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
	Plan *string `pulumi:"plan"`
	// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
	Project *string `pulumi:"project"`
	// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
	ProjectVpcId *string `pulumi:"projectVpcId"`
	// The hostname of the service.
	ServiceHost *string `pulumi:"serviceHost"`
	// Service integrations to specify when creating a service. Not applied after initial service creation
	ServiceIntegrations []ThanosServiceIntegration `pulumi:"serviceIntegrations"`
	// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
	ServiceName *string `pulumi:"serviceName"`
	// Password used for connecting to the service, if applicable
	ServicePassword *string `pulumi:"servicePassword"`
	// The port of the service
	ServicePort *int `pulumi:"servicePort"`
	// Aiven internal service type code
	ServiceType *string `pulumi:"serviceType"`
	// URI for connecting to the service. Service specific info is under "kafka", "pg", etc.
	ServiceUri *string `pulumi:"serviceUri"`
	// Username used for connecting to the service, if applicable
	ServiceUsername *string `pulumi:"serviceUsername"`
	State           *string `pulumi:"state"`
	// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
	StaticIps []string `pulumi:"staticIps"`
	// Tags are key-value pairs that allow you to categorize services.
	Tags []ThanosTag `pulumi:"tags"`
	// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
	TechEmails []ThanosTechEmail `pulumi:"techEmails"`
	// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
	TerminationProtection *bool `pulumi:"terminationProtection"`
	// Thanos server connection details.
	Thanos *ThanosThanos `pulumi:"thanos"`
	// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
	ThanosUserConfig *ThanosThanosUserConfig `pulumi:"thanosUserConfig"`
}

type ThanosState struct {
	// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
	AdditionalDiskSpace pulumi.StringPtrInput
	// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
	CloudName pulumi.StringPtrInput
	// Service component information objects
	Components ThanosComponentArrayInput
	// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	//
	// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	DiskSpace pulumi.StringPtrInput
	// The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
	DiskSpaceCap pulumi.StringPtrInput
	// The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `diskSpace`
	DiskSpaceDefault pulumi.StringPtrInput
	// The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `diskSpace` needs to increment from `diskSpaceDefault` by increments of this size.
	DiskSpaceStep pulumi.StringPtrInput
	// The disk space that the service is currently using. This is the sum of `diskSpace` and `additionalDiskSpace` in human-readable format (for example: `90GiB`).
	DiskSpaceUsed pulumi.StringPtrInput
	// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
	MaintenanceWindowDow pulumi.StringPtrInput
	// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
	MaintenanceWindowTime pulumi.StringPtrInput
	// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
	Plan pulumi.StringPtrInput
	// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
	Project pulumi.StringPtrInput
	// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
	ProjectVpcId pulumi.StringPtrInput
	// The hostname of the service.
	ServiceHost pulumi.StringPtrInput
	// Service integrations to specify when creating a service. Not applied after initial service creation
	ServiceIntegrations ThanosServiceIntegrationArrayInput
	// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
	ServiceName pulumi.StringPtrInput
	// Password used for connecting to the service, if applicable
	ServicePassword pulumi.StringPtrInput
	// The port of the service
	ServicePort pulumi.IntPtrInput
	// Aiven internal service type code
	ServiceType pulumi.StringPtrInput
	// URI for connecting to the service. Service specific info is under "kafka", "pg", etc.
	ServiceUri pulumi.StringPtrInput
	// Username used for connecting to the service, if applicable
	ServiceUsername pulumi.StringPtrInput
	State           pulumi.StringPtrInput
	// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
	StaticIps pulumi.StringArrayInput
	// Tags are key-value pairs that allow you to categorize services.
	Tags ThanosTagArrayInput
	// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
	TechEmails ThanosTechEmailArrayInput
	// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
	TerminationProtection pulumi.BoolPtrInput
	// Thanos server connection details.
	Thanos ThanosThanosPtrInput
	// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
	ThanosUserConfig ThanosThanosUserConfigPtrInput
}

func (ThanosState) ElementType() reflect.Type {
	return reflect.TypeOf((*thanosState)(nil)).Elem()
}

type thanosArgs struct {
	// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
	AdditionalDiskSpace *string `pulumi:"additionalDiskSpace"`
	// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
	CloudName *string `pulumi:"cloudName"`
	// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	//
	// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	DiskSpace *string `pulumi:"diskSpace"`
	// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
	MaintenanceWindowDow *string `pulumi:"maintenanceWindowDow"`
	// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
	MaintenanceWindowTime *string `pulumi:"maintenanceWindowTime"`
	// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
	Plan string `pulumi:"plan"`
	// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
	Project string `pulumi:"project"`
	// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
	ProjectVpcId *string `pulumi:"projectVpcId"`
	// Service integrations to specify when creating a service. Not applied after initial service creation
	ServiceIntegrations []ThanosServiceIntegration `pulumi:"serviceIntegrations"`
	// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
	ServiceName string `pulumi:"serviceName"`
	// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
	StaticIps []string `pulumi:"staticIps"`
	// Tags are key-value pairs that allow you to categorize services.
	Tags []ThanosTag `pulumi:"tags"`
	// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
	TechEmails []ThanosTechEmail `pulumi:"techEmails"`
	// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
	TerminationProtection *bool `pulumi:"terminationProtection"`
	// Thanos server connection details.
	Thanos *ThanosThanos `pulumi:"thanos"`
	// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
	ThanosUserConfig *ThanosThanosUserConfig `pulumi:"thanosUserConfig"`
}

// The set of arguments for constructing a Thanos resource.
type ThanosArgs struct {
	// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
	AdditionalDiskSpace pulumi.StringPtrInput
	// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
	CloudName pulumi.StringPtrInput
	// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	//
	// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
	DiskSpace pulumi.StringPtrInput
	// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
	MaintenanceWindowDow pulumi.StringPtrInput
	// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
	MaintenanceWindowTime pulumi.StringPtrInput
	// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
	Plan pulumi.StringInput
	// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
	Project pulumi.StringInput
	// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
	ProjectVpcId pulumi.StringPtrInput
	// Service integrations to specify when creating a service. Not applied after initial service creation
	ServiceIntegrations ThanosServiceIntegrationArrayInput
	// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
	ServiceName pulumi.StringInput
	// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
	StaticIps pulumi.StringArrayInput
	// Tags are key-value pairs that allow you to categorize services.
	Tags ThanosTagArrayInput
	// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
	TechEmails ThanosTechEmailArrayInput
	// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
	TerminationProtection pulumi.BoolPtrInput
	// Thanos server connection details.
	Thanos ThanosThanosPtrInput
	// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
	ThanosUserConfig ThanosThanosUserConfigPtrInput
}

func (ThanosArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*thanosArgs)(nil)).Elem()
}

type ThanosInput interface {
	pulumi.Input

	ToThanosOutput() ThanosOutput
	ToThanosOutputWithContext(ctx context.Context) ThanosOutput
}

func (*Thanos) ElementType() reflect.Type {
	return reflect.TypeOf((**Thanos)(nil)).Elem()
}

func (i *Thanos) ToThanosOutput() ThanosOutput {
	return i.ToThanosOutputWithContext(context.Background())
}

func (i *Thanos) ToThanosOutputWithContext(ctx context.Context) ThanosOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ThanosOutput)
}

// ThanosArrayInput is an input type that accepts ThanosArray and ThanosArrayOutput values.
// You can construct a concrete instance of `ThanosArrayInput` via:
//
//	ThanosArray{ ThanosArgs{...} }
type ThanosArrayInput interface {
	pulumi.Input

	ToThanosArrayOutput() ThanosArrayOutput
	ToThanosArrayOutputWithContext(context.Context) ThanosArrayOutput
}

type ThanosArray []ThanosInput

func (ThanosArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Thanos)(nil)).Elem()
}

func (i ThanosArray) ToThanosArrayOutput() ThanosArrayOutput {
	return i.ToThanosArrayOutputWithContext(context.Background())
}

func (i ThanosArray) ToThanosArrayOutputWithContext(ctx context.Context) ThanosArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ThanosArrayOutput)
}

// ThanosMapInput is an input type that accepts ThanosMap and ThanosMapOutput values.
// You can construct a concrete instance of `ThanosMapInput` via:
//
//	ThanosMap{ "key": ThanosArgs{...} }
type ThanosMapInput interface {
	pulumi.Input

	ToThanosMapOutput() ThanosMapOutput
	ToThanosMapOutputWithContext(context.Context) ThanosMapOutput
}

type ThanosMap map[string]ThanosInput

func (ThanosMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Thanos)(nil)).Elem()
}

func (i ThanosMap) ToThanosMapOutput() ThanosMapOutput {
	return i.ToThanosMapOutputWithContext(context.Background())
}

func (i ThanosMap) ToThanosMapOutputWithContext(ctx context.Context) ThanosMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ThanosMapOutput)
}

type ThanosOutput struct{ *pulumi.OutputState }

func (ThanosOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Thanos)(nil)).Elem()
}

func (o ThanosOutput) ToThanosOutput() ThanosOutput {
	return o
}

func (o ThanosOutput) ToThanosOutputWithContext(ctx context.Context) ThanosOutput {
	return o
}

// Add [disk storage](https://aiven.io/docs/platform/howto/add-storage-space) in increments of 30  GiB to scale your service. The maximum value depends on the service type and cloud provider. Removing additional storage causes the service nodes to go through a rolling restart, and there might be a short downtime for services without an autoscaler integration or high availability capabilities. The field can be safely removed when autoscaler is enabled without causing any changes.
func (o ThanosOutput) AdditionalDiskSpace() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.AdditionalDiskSpace }).(pulumi.StringOutput)
}

// The cloud provider and region the service is hosted in. The format is `provider-region`, for example: `google-europe-west1`. The [available cloud regions](https://aiven.io/docs/platform/reference/list_of_clouds) can differ per project and service. Changing this value [migrates the service to another cloud provider or region](https://aiven.io/docs/platform/howto/migrate-services-cloud-region). The migration runs in the background and includes a DNS update to redirect traffic to the new region. Most services experience no downtime, but some databases may have a brief interruption during DNS propagation.
func (o ThanosOutput) CloudName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringPtrOutput { return v.CloudName }).(pulumi.StringPtrOutput)
}

// Service component information objects
func (o ThanosOutput) Components() ThanosComponentArrayOutput {
	return o.ApplyT(func(v *Thanos) ThanosComponentArrayOutput { return v.Components }).(ThanosComponentArrayOutput)
}

// Service disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing. Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
//
// Deprecated: Please use `additionalDiskSpace` to specify the space to be added to the default disk space defined by the plan.
func (o ThanosOutput) DiskSpace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringPtrOutput { return v.DiskSpace }).(pulumi.StringPtrOutput)
}

// The maximum disk space of the service, possible values depend on the service type, the cloud provider and the project.
func (o ThanosOutput) DiskSpaceCap() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.DiskSpaceCap }).(pulumi.StringOutput)
}

// The default disk space of the service, possible values depend on the service type, the cloud provider and the project. Its also the minimum value for `diskSpace`
func (o ThanosOutput) DiskSpaceDefault() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.DiskSpaceDefault }).(pulumi.StringOutput)
}

// The default disk space step of the service, possible values depend on the service type, the cloud provider and the project. `diskSpace` needs to increment from `diskSpaceDefault` by increments of this size.
func (o ThanosOutput) DiskSpaceStep() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.DiskSpaceStep }).(pulumi.StringOutput)
}

// The disk space that the service is currently using. This is the sum of `diskSpace` and `additionalDiskSpace` in human-readable format (for example: `90GiB`).
func (o ThanosOutput) DiskSpaceUsed() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.DiskSpaceUsed }).(pulumi.StringOutput)
}

// Day of week when maintenance operations should be performed. One monday, tuesday, wednesday, etc.
func (o ThanosOutput) MaintenanceWindowDow() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringPtrOutput { return v.MaintenanceWindowDow }).(pulumi.StringPtrOutput)
}

// Time of day when maintenance operations should be performed. UTC time in HH:mm:ss format.
func (o ThanosOutput) MaintenanceWindowTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringPtrOutput { return v.MaintenanceWindowTime }).(pulumi.StringPtrOutput)
}

// Defines what kind of computing resources are allocated for the service. It can be changed after creation, though there are some restrictions when going to a smaller plan such as the new plan must have sufficient amount of disk space to store all current data and switching to a plan with fewer nodes might not be supported. The basic plan names are `hobbyist`, `startup-x`, `business-x` and `premium-x` where `x` is (roughly) the amount of memory on each node (also other attributes like number of CPUs and amount of disk space varies but naming is based on memory). The available options can be seen from the [Aiven pricing page](https://aiven.io/pricing).
func (o ThanosOutput) Plan() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.Plan }).(pulumi.StringOutput)
}

// The name of the project this resource belongs to. To set up proper dependencies please refer to this variable as a reference. Changing this property forces recreation of the resource.
func (o ThanosOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Specifies the VPC the service should run in. If the value is not set, the service runs on the Public Internet. When set, the value should be given as a reference to set up dependencies correctly, and the VPC must be in the same cloud and region as the service itself. The service can be freely moved to and from VPC after creation, but doing so triggers migration to new servers, so the operation can take a significant amount of time to complete if the service has a lot of data.
func (o ThanosOutput) ProjectVpcId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringPtrOutput { return v.ProjectVpcId }).(pulumi.StringPtrOutput)
}

// The hostname of the service.
func (o ThanosOutput) ServiceHost() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServiceHost }).(pulumi.StringOutput)
}

// Service integrations to specify when creating a service. Not applied after initial service creation
func (o ThanosOutput) ServiceIntegrations() ThanosServiceIntegrationArrayOutput {
	return o.ApplyT(func(v *Thanos) ThanosServiceIntegrationArrayOutput { return v.ServiceIntegrations }).(ThanosServiceIntegrationArrayOutput)
}

// Specifies the actual name of the service. The name cannot be changed later without destroying and re-creating the service so name should be picked based on intended service usage rather than current attributes.
func (o ThanosOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServiceName }).(pulumi.StringOutput)
}

// Password used for connecting to the service, if applicable
func (o ThanosOutput) ServicePassword() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServicePassword }).(pulumi.StringOutput)
}

// The port of the service
func (o ThanosOutput) ServicePort() pulumi.IntOutput {
	return o.ApplyT(func(v *Thanos) pulumi.IntOutput { return v.ServicePort }).(pulumi.IntOutput)
}

// Aiven internal service type code
func (o ThanosOutput) ServiceType() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServiceType }).(pulumi.StringOutput)
}

// URI for connecting to the service. Service specific info is under "kafka", "pg", etc.
func (o ThanosOutput) ServiceUri() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServiceUri }).(pulumi.StringOutput)
}

// Username used for connecting to the service, if applicable
func (o ThanosOutput) ServiceUsername() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.ServiceUsername }).(pulumi.StringOutput)
}

func (o ThanosOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Static IPs that are going to be associated with this service. Please assign a value using the 'toset' function. Once a static ip resource is in the 'assigned' state it cannot be unbound from the node again
func (o ThanosOutput) StaticIps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Thanos) pulumi.StringArrayOutput { return v.StaticIps }).(pulumi.StringArrayOutput)
}

// Tags are key-value pairs that allow you to categorize services.
func (o ThanosOutput) Tags() ThanosTagArrayOutput {
	return o.ApplyT(func(v *Thanos) ThanosTagArrayOutput { return v.Tags }).(ThanosTagArrayOutput)
}

// The email addresses for [service contacts](https://aiven.io/docs/platform/howto/technical-emails), who will receive important alerts and updates about this service. You can also set email contacts at the project level.
func (o ThanosOutput) TechEmails() ThanosTechEmailArrayOutput {
	return o.ApplyT(func(v *Thanos) ThanosTechEmailArrayOutput { return v.TechEmails }).(ThanosTechEmailArrayOutput)
}

// Prevents the service from being deleted. It is recommended to set this to `true` for all production services to prevent unintentional service deletion. This does not shield against deleting databases or topics but for services with backups much of the content can at least be restored from backup in case accidental deletion is done.
func (o ThanosOutput) TerminationProtection() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Thanos) pulumi.BoolPtrOutput { return v.TerminationProtection }).(pulumi.BoolPtrOutput)
}

// Thanos server connection details.
func (o ThanosOutput) Thanos() ThanosThanosOutput {
	return o.ApplyT(func(v *Thanos) ThanosThanosOutput { return v.Thanos }).(ThanosThanosOutput)
}

// Thanos user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later
func (o ThanosOutput) ThanosUserConfig() ThanosThanosUserConfigPtrOutput {
	return o.ApplyT(func(v *Thanos) ThanosThanosUserConfigPtrOutput { return v.ThanosUserConfig }).(ThanosThanosUserConfigPtrOutput)
}

type ThanosArrayOutput struct{ *pulumi.OutputState }

func (ThanosArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Thanos)(nil)).Elem()
}

func (o ThanosArrayOutput) ToThanosArrayOutput() ThanosArrayOutput {
	return o
}

func (o ThanosArrayOutput) ToThanosArrayOutputWithContext(ctx context.Context) ThanosArrayOutput {
	return o
}

func (o ThanosArrayOutput) Index(i pulumi.IntInput) ThanosOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Thanos {
		return vs[0].([]*Thanos)[vs[1].(int)]
	}).(ThanosOutput)
}

type ThanosMapOutput struct{ *pulumi.OutputState }

func (ThanosMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Thanos)(nil)).Elem()
}

func (o ThanosMapOutput) ToThanosMapOutput() ThanosMapOutput {
	return o
}

func (o ThanosMapOutput) ToThanosMapOutputWithContext(ctx context.Context) ThanosMapOutput {
	return o
}

func (o ThanosMapOutput) MapIndex(k pulumi.StringInput) ThanosOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Thanos {
		return vs[0].(map[string]*Thanos)[vs[1].(string)]
	}).(ThanosOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ThanosInput)(nil)).Elem(), &Thanos{})
	pulumi.RegisterInputType(reflect.TypeOf((*ThanosArrayInput)(nil)).Elem(), ThanosArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ThanosMapInput)(nil)).Elem(), ThanosMap{})
	pulumi.RegisterOutputType(ThanosOutput{})
	pulumi.RegisterOutputType(ThanosArrayOutput{})
	pulumi.RegisterOutputType(ThanosMapOutput{})
}
