// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven;

import com.pulumi.aiven.AzureVpcPeeringConnectionArgs;
import com.pulumi.aiven.Utilities;
import com.pulumi.aiven.inputs.AzureVpcPeeringConnectionState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import javax.annotation.Nullable;

/**
 * The Azure VPC Peering Connection resource allows the creation and management of Aiven VPC Peering Connections.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aiven.AzureVpcPeeringConnection;
 * import com.pulumi.aiven.AzureVpcPeeringConnectionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var foo = new AzureVpcPeeringConnection(&#34;foo&#34;, AzureVpcPeeringConnectionArgs.builder()        
 *             .vpcId(data.aiven_project_vpc().vpc().id())
 *             .azureSubscriptionId(&#34;xxxxxx&#34;)
 *             .peerResourceGroup(&#34;my-pr1&#34;)
 *             .vnetName(&#34;my-vnet1&#34;)
 *             .peerAzureAppId(&#34;xxxxxx&#34;)
 *             .peerAzureTenantId(&#34;xxxxxx&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import aiven:index/azureVpcPeeringConnection:AzureVpcPeeringConnection foo project_name/vpc_id/azure_subscription_id/vnet_name
 * ```
 * 
 */
@ResourceType(type="aiven:index/azureVpcPeeringConnection:AzureVpcPeeringConnection")
public class AzureVpcPeeringConnection extends com.pulumi.resources.CustomResource {
    /**
     * Azure Subscription ID. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="azureSubscriptionId", refs={String.class}, tree="[0]")
    private Output<String> azureSubscriptionId;

    /**
     * @return Azure Subscription ID. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> azureSubscriptionId() {
        return this.azureSubscriptionId;
    }
    /**
     * Azure app registration id in UUID4 form that is allowed to create a peering to the peer vnet. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="peerAzureAppId", refs={String.class}, tree="[0]")
    private Output<String> peerAzureAppId;

    /**
     * @return Azure app registration id in UUID4 form that is allowed to create a peering to the peer vnet. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> peerAzureAppId() {
        return this.peerAzureAppId;
    }
    /**
     * Azure tenant id in UUID4 form. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="peerAzureTenantId", refs={String.class}, tree="[0]")
    private Output<String> peerAzureTenantId;

    /**
     * @return Azure tenant id in UUID4 form. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> peerAzureTenantId() {
        return this.peerAzureTenantId;
    }
    /**
     * Azure resource group name of the peered VPC. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="peerResourceGroup", refs={String.class}, tree="[0]")
    private Output<String> peerResourceGroup;

    /**
     * @return Azure resource group name of the peered VPC. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> peerResourceGroup() {
        return this.peerResourceGroup;
    }
    /**
     * Cloud provider identifier for the peering connection if available
     * 
     */
    @Export(name="peeringConnectionId", refs={String.class}, tree="[0]")
    private Output<String> peeringConnectionId;

    /**
     * @return Cloud provider identifier for the peering connection if available
     * 
     */
    public Output<String> peeringConnectionId() {
        return this.peeringConnectionId;
    }
    /**
     * State of the peering connection
     * 
     */
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output<String> state;

    /**
     * @return State of the peering connection
     * 
     */
    public Output<String> state() {
        return this.state;
    }
    /**
     * State-specific help or error information
     * 
     */
    @Export(name="stateInfo", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> stateInfo;

    /**
     * @return State-specific help or error information
     * 
     */
    public Output<Map<String,Object>> stateInfo() {
        return this.stateInfo;
    }
    /**
     * Azure Network name. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="vnetName", refs={String.class}, tree="[0]")
    private Output<String> vnetName;

    /**
     * @return Azure Network name. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> vnetName() {
        return this.vnetName;
    }
    /**
     * The VPC the peering connection belongs to. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    @Export(name="vpcId", refs={String.class}, tree="[0]")
    private Output<String> vpcId;

    /**
     * @return The VPC the peering connection belongs to. This property cannot be changed, doing so forces recreation of the resource.
     * 
     */
    public Output<String> vpcId() {
        return this.vpcId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AzureVpcPeeringConnection(String name) {
        this(name, AzureVpcPeeringConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AzureVpcPeeringConnection(String name, AzureVpcPeeringConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AzureVpcPeeringConnection(String name, AzureVpcPeeringConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aiven:index/azureVpcPeeringConnection:AzureVpcPeeringConnection", name, args == null ? AzureVpcPeeringConnectionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private AzureVpcPeeringConnection(String name, Output<String> id, @Nullable AzureVpcPeeringConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("aiven:index/azureVpcPeeringConnection:AzureVpcPeeringConnection", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AzureVpcPeeringConnection get(String name, Output<String> id, @Nullable AzureVpcPeeringConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AzureVpcPeeringConnection(name, id, state, options);
    }
}
