// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.aiven;

import com.pulumi.aiven.inputs.MysqlUserTimeoutsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MysqlUserArgs extends com.pulumi.resources.ResourceArgs {

    public static final MysqlUserArgs Empty = new MysqlUserArgs();

    /**
     * Service specific authentication details. Currently only used for MySQL where accepted options are &#39;mysql_native_password&#39; and &#39;caching_sha2_password&#39;, latter being default when this is not explicitly set. The possible values are `cachingSha2Password` and `mysqlNativePassword`.
     * 
     */
    @Import(name="authentication")
    private @Nullable Output<String> authentication;

    /**
     * @return Service specific authentication details. Currently only used for MySQL where accepted options are &#39;mysql_native_password&#39; and &#39;caching_sha2_password&#39;, latter being default when this is not explicitly set. The possible values are `cachingSha2Password` and `mysqlNativePassword`.
     * 
     */
    public Optional<Output<String>> authentication() {
        return Optional.ofNullable(this.authentication);
    }

    /**
     * The password of the service user (auto-generated if not provided). The field conflicts with `passwordWo`. Value must be between `8` and `256`.
     * 
     */
    @Import(name="password")
    private @Nullable Output<String> password;

    /**
     * @return The password of the service user (auto-generated if not provided). The field conflicts with `passwordWo`. Value must be between `8` and `256`.
     * 
     */
    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The password of the service user (write-only, not stored in state). The field is required with `passwordWoVersion`. The field conflicts with `password`. Value must be between `8` and `256`.
     * 
     */
    @Import(name="passwordWo")
    private @Nullable Output<String> passwordWo;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The password of the service user (write-only, not stored in state). The field is required with `passwordWoVersion`. The field conflicts with `password`. Value must be between `8` and `256`.
     * 
     */
    public Optional<Output<String>> passwordWo() {
        return Optional.ofNullable(this.passwordWo);
    }

    /**
     * Version number for `passwordWo`. Increment this to rotate the password. The field is required with `passwordWo`. Minimum value: `1`.
     * 
     */
    @Import(name="passwordWoVersion")
    private @Nullable Output<Integer> passwordWoVersion;

    /**
     * @return Version number for `passwordWo`. Increment this to rotate the password. The field is required with `passwordWo`. Minimum value: `1`.
     * 
     */
    public Optional<Output<Integer>> passwordWoVersion() {
        return Optional.ofNullable(this.passwordWoVersion);
    }

    /**
     * Project name. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="project", required=true)
    private Output<String> project;

    /**
     * @return Project name. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> project() {
        return this.project;
    }

    /**
     * The name of the MySQL® service user. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="serviceName", required=true)
    private Output<String> serviceName;

    /**
     * @return The name of the MySQL® service user. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> serviceName() {
        return this.serviceName;
    }

    @Import(name="timeouts")
    private @Nullable Output<MysqlUserTimeoutsArgs> timeouts;

    public Optional<Output<MysqlUserTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    /**
     * The name of the MySQL® service user. Maximum length: `64`. Changing this property forces recreation of the resource.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The name of the MySQL® service user. Maximum length: `64`. Changing this property forces recreation of the resource.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private MysqlUserArgs() {}

    private MysqlUserArgs(MysqlUserArgs $) {
        this.authentication = $.authentication;
        this.password = $.password;
        this.passwordWo = $.passwordWo;
        this.passwordWoVersion = $.passwordWoVersion;
        this.project = $.project;
        this.serviceName = $.serviceName;
        this.timeouts = $.timeouts;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MysqlUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MysqlUserArgs $;

        public Builder() {
            $ = new MysqlUserArgs();
        }

        public Builder(MysqlUserArgs defaults) {
            $ = new MysqlUserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param authentication Service specific authentication details. Currently only used for MySQL where accepted options are &#39;mysql_native_password&#39; and &#39;caching_sha2_password&#39;, latter being default when this is not explicitly set. The possible values are `cachingSha2Password` and `mysqlNativePassword`.
         * 
         * @return builder
         * 
         */
        public Builder authentication(@Nullable Output<String> authentication) {
            $.authentication = authentication;
            return this;
        }

        /**
         * @param authentication Service specific authentication details. Currently only used for MySQL where accepted options are &#39;mysql_native_password&#39; and &#39;caching_sha2_password&#39;, latter being default when this is not explicitly set. The possible values are `cachingSha2Password` and `mysqlNativePassword`.
         * 
         * @return builder
         * 
         */
        public Builder authentication(String authentication) {
            return authentication(Output.of(authentication));
        }

        /**
         * @param password The password of the service user (auto-generated if not provided). The field conflicts with `passwordWo`. Value must be between `8` and `256`.
         * 
         * @return builder
         * 
         */
        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password The password of the service user (auto-generated if not provided). The field conflicts with `passwordWo`. Value must be between `8` and `256`.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param passwordWo **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * The password of the service user (write-only, not stored in state). The field is required with `passwordWoVersion`. The field conflicts with `password`. Value must be between `8` and `256`.
         * 
         * @return builder
         * 
         */
        public Builder passwordWo(@Nullable Output<String> passwordWo) {
            $.passwordWo = passwordWo;
            return this;
        }

        /**
         * @param passwordWo **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * The password of the service user (write-only, not stored in state). The field is required with `passwordWoVersion`. The field conflicts with `password`. Value must be between `8` and `256`.
         * 
         * @return builder
         * 
         */
        public Builder passwordWo(String passwordWo) {
            return passwordWo(Output.of(passwordWo));
        }

        /**
         * @param passwordWoVersion Version number for `passwordWo`. Increment this to rotate the password. The field is required with `passwordWo`. Minimum value: `1`.
         * 
         * @return builder
         * 
         */
        public Builder passwordWoVersion(@Nullable Output<Integer> passwordWoVersion) {
            $.passwordWoVersion = passwordWoVersion;
            return this;
        }

        /**
         * @param passwordWoVersion Version number for `passwordWo`. Increment this to rotate the password. The field is required with `passwordWo`. Minimum value: `1`.
         * 
         * @return builder
         * 
         */
        public Builder passwordWoVersion(Integer passwordWoVersion) {
            return passwordWoVersion(Output.of(passwordWoVersion));
        }

        /**
         * @param project Project name. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder project(Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project Project name. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param serviceName The name of the MySQL® service user. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName The name of the MySQL® service user. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        public Builder timeouts(@Nullable Output<MysqlUserTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(MysqlUserTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        /**
         * @param username The name of the MySQL® service user. Maximum length: `64`. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The name of the MySQL® service user. Maximum length: `64`. Changing this property forces recreation of the resource.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public MysqlUserArgs build() {
            if ($.project == null) {
                throw new MissingRequiredPropertyException("MysqlUserArgs", "project");
            }
            if ($.serviceName == null) {
                throw new MissingRequiredPropertyException("MysqlUserArgs", "serviceName");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("MysqlUserArgs", "username");
            }
            return $;
        }
    }

}
