// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class GetKafkaKafkaUserConfigInputArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Serve the web frontend using a custom CNAME pointing to the Aiven DNS name.
        /// </summary>
        [Input("customDomain")]
        public Input<string>? CustomDomain { get; set; }

        [Input("ipFilters")]
        private InputList<string>? _ipFilters;

        /// <summary>
        /// Allow incoming connections from CIDR address block, e.g. '10.20.0.0/16'.
        /// </summary>
        public InputList<string> IpFilters
        {
            get => _ipFilters ?? (_ipFilters = new InputList<string>());
            set => _ipFilters = value;
        }

        /// <summary>
        /// Kafka server provided values:
        /// </summary>
        [Input("kafka")]
        public Input<Inputs.GetKafkaKafkaUserConfigKafkaInputArgs>? Kafka { get; set; }

        /// <summary>
        /// Kafka authentication methods
        /// </summary>
        [Input("kafkaAuthenticationMethods")]
        public Input<Inputs.GetKafkaKafkaUserConfigKafkaAuthenticationMethodsInputArgs>? KafkaAuthenticationMethods { get; set; }

        /// <summary>
        /// Enable kafka_connect
        /// </summary>
        [Input("kafkaConnect")]
        public Input<string>? KafkaConnect { get; set; }

        /// <summary>
        /// Kafka Connect configuration values
        /// </summary>
        [Input("kafkaConnectConfig")]
        public Input<Inputs.GetKafkaKafkaUserConfigKafkaConnectConfigInputArgs>? KafkaConnectConfig { get; set; }

        /// <summary>
        /// Enable kafka_rest
        /// </summary>
        [Input("kafkaRest")]
        public Input<string>? KafkaRest { get; set; }

        /// <summary>
        /// Kafka-REST configuration
        /// </summary>
        [Input("kafkaRestConfig")]
        public Input<Inputs.GetKafkaKafkaUserConfigKafkaRestConfigInputArgs>? KafkaRestConfig { get; set; }

        /// <summary>
        /// Kafka major version
        /// </summary>
        [Input("kafkaVersion")]
        public Input<string>? KafkaVersion { get; set; }

        /// <summary>
        /// Allow access to selected service ports from private networks
        /// </summary>
        [Input("privateAccess")]
        public Input<Inputs.GetKafkaKafkaUserConfigPrivateAccessInputArgs>? PrivateAccess { get; set; }

        /// <summary>
        /// Allow access to selected service components through Privatelink
        /// </summary>
        [Input("privatelinkAccess")]
        public Input<Inputs.GetKafkaKafkaUserConfigPrivatelinkAccessInputArgs>? PrivatelinkAccess { get; set; }

        /// <summary>
        /// Allow access to selected service ports from the public Internet
        /// </summary>
        [Input("publicAccess")]
        public Input<Inputs.GetKafkaKafkaUserConfigPublicAccessInputArgs>? PublicAccess { get; set; }

        /// <summary>
        /// Enable schema_registry
        /// </summary>
        [Input("schemaRegistry")]
        public Input<string>? SchemaRegistry { get; set; }

        /// <summary>
        /// Schema Registry configuration
        /// </summary>
        [Input("schemaRegistryConfig")]
        public Input<Inputs.GetKafkaKafkaUserConfigSchemaRegistryConfigInputArgs>? SchemaRegistryConfig { get; set; }

        [Input("staticIps")]
        public Input<string>? StaticIps { get; set; }

        public GetKafkaKafkaUserConfigInputArgs()
        {
        }
    }
}
