// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class GetOrganizationBillingGroupListBillingGroupInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Billing address ID.
        /// </summary>
        [Input("billingAddressId", required: true)]
        public Input<string> BillingAddressId { get; set; } = null!;

        [Input("billingContactEmails")]
        private InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingContactEmailInputArgs>? _billingContactEmails;

        /// <summary>
        /// List of billing contact emails.
        /// </summary>
        public InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingContactEmailInputArgs> BillingContactEmails
        {
            get => _billingContactEmails ?? (_billingContactEmails = new InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingContactEmailInputArgs>());
            set => _billingContactEmails = value;
        }

        [Input("billingEmails")]
        private InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingEmailInputArgs>? _billingEmails;

        /// <summary>
        /// List of billing contact emails.
        /// </summary>
        public InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingEmailInputArgs> BillingEmails
        {
            get => _billingEmails ?? (_billingEmails = new InputList<Inputs.GetOrganizationBillingGroupListBillingGroupBillingEmailInputArgs>());
            set => _billingEmails = value;
        }

        /// <summary>
        /// Billing group ID.
        /// </summary>
        [Input("billingGroupId", required: true)]
        public Input<string> BillingGroupId { get; set; } = null!;

        /// <summary>
        /// Billing Group Name.
        /// </summary>
        [Input("billingGroupName", required: true)]
        public Input<string> BillingGroupName { get; set; } = null!;

        /// <summary>
        /// Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.
        /// </summary>
        [Input("currency", required: true)]
        public Input<string> Currency { get; set; } = null!;

        /// <summary>
        /// Extra billing text.
        /// </summary>
        [Input("customInvoiceText", required: true)]
        public Input<string> CustomInvoiceText { get; set; } = null!;

        /// <summary>
        /// Organization ID.
        /// </summary>
        [Input("organizationId", required: true)]
        public Input<string> OrganizationId { get; set; } = null!;

        [Input("paymentMethods")]
        private InputList<Inputs.GetOrganizationBillingGroupListBillingGroupPaymentMethodInputArgs>? _paymentMethods;

        /// <summary>
        /// Payment method.
        /// </summary>
        public InputList<Inputs.GetOrganizationBillingGroupListBillingGroupPaymentMethodInputArgs> PaymentMethods
        {
            get => _paymentMethods ?? (_paymentMethods = new InputList<Inputs.GetOrganizationBillingGroupListBillingGroupPaymentMethodInputArgs>());
            set => _paymentMethods = value;
        }

        /// <summary>
        /// Shipping address ID.
        /// </summary>
        [Input("shippingAddressId", required: true)]
        public Input<string> ShippingAddressId { get; set; } = null!;

        /// <summary>
        /// VAT ID.
        /// </summary>
        [Input("vatId", required: true)]
        public Input<string> VatId { get; set; } = null!;

        public GetOrganizationBillingGroupListBillingGroupInputArgs()
        {
        }
        public static new GetOrganizationBillingGroupListBillingGroupInputArgs Empty => new GetOrganizationBillingGroupListBillingGroupInputArgs();
    }
}
