// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class GetOpenSearchOpensearchArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// URI for Opensearch dashboards frontend.
        /// </summary>
        [Input("opensearchDashboardsUri", required: true)]
        public string OpensearchDashboardsUri { get; set; } = null!;

        public GetOpenSearchOpensearchArgs()
        {
        }
    }
}
