// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class GetServicePlanListServicePlanArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Maximum amount of system memory as a percentage (0-100) the service can actually use after taking into account management overhead. This is relevant for memory bound services for which some service management operations require allocating proportional amount of memory on top the basic load.
        /// </summary>
        [Input("maxMemoryPercent", required: true)]
        public int MaxMemoryPercent { get; set; }

        /// <summary>
        /// Number of nodes in this service plan.
        /// </summary>
        [Input("nodeCount", required: true)]
        public int NodeCount { get; set; }

        [Input("regions", required: true)]
        private Dictionary<string, Inputs.GetServicePlanListServicePlanRegionsArgs>? _regions;

        /// <summary>
        /// Service plan hourly price per cloud region.
        /// </summary>
        public Dictionary<string, Inputs.GetServicePlanListServicePlanRegionsArgs> Regions
        {
            get => _regions ?? (_regions = new Dictionary<string, Inputs.GetServicePlanListServicePlanRegionsArgs>());
            set => _regions = value;
        }

        /// <summary>
        /// Subscription plan.
        /// </summary>
        [Input("servicePlan", required: true)]
        public string ServicePlan { get; set; } = null!;

        /// <summary>
        /// Service type code.
        /// </summary>
        [Input("serviceType", required: true)]
        public string ServiceType { get; set; } = null!;

        /// <summary>
        /// Number of shards in this service plan.
        /// </summary>
        [Input("shardCount", required: true)]
        public int ShardCount { get; set; }

        public GetServicePlanListServicePlanArgs()
        {
        }
        public static new GetServicePlanListServicePlanArgs Empty => new GetServicePlanListServicePlanArgs();
    }
}
