// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class KafkaMirrorMakerKafkaMirrormakerUserConfigKafkaMirrormakerArgs : global::Pulumi.ResourceArgs
    {
        [Input("emitCheckpointsEnabled")]
        public Input<bool>? EmitCheckpointsEnabled { get; set; }

        [Input("emitCheckpointsIntervalSeconds")]
        public Input<int>? EmitCheckpointsIntervalSeconds { get; set; }

        [Input("refreshGroupsEnabled")]
        public Input<bool>? RefreshGroupsEnabled { get; set; }

        [Input("refreshGroupsIntervalSeconds")]
        public Input<int>? RefreshGroupsIntervalSeconds { get; set; }

        [Input("refreshTopicsEnabled")]
        public Input<bool>? RefreshTopicsEnabled { get; set; }

        [Input("refreshTopicsIntervalSeconds")]
        public Input<int>? RefreshTopicsIntervalSeconds { get; set; }

        [Input("syncGroupOffsetsEnabled")]
        public Input<bool>? SyncGroupOffsetsEnabled { get; set; }

        [Input("syncGroupOffsetsIntervalSeconds")]
        public Input<int>? SyncGroupOffsetsIntervalSeconds { get; set; }

        [Input("syncTopicConfigsEnabled")]
        public Input<bool>? SyncTopicConfigsEnabled { get; set; }

        [Input("tasksMaxPerCpu")]
        public Input<int>? TasksMaxPerCpu { get; set; }

        public KafkaMirrorMakerKafkaMirrormakerUserConfigKafkaMirrormakerArgs()
        {
        }
        public static new KafkaMirrorMakerKafkaMirrormakerUserConfigKafkaMirrormakerArgs Empty => new KafkaMirrorMakerKafkaMirrormakerUserConfigKafkaMirrormakerArgs();
    }
}
