// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class M3DbM3dbUserConfigRulesMappingArgs : global::Pulumi.ResourceArgs
    {
        [Input("aggregations")]
        private InputList<string>? _aggregations;
        public InputList<string> Aggregations
        {
            get => _aggregations ?? (_aggregations = new InputList<string>());
            set => _aggregations = value;
        }

        [Input("drop")]
        public Input<string>? Drop { get; set; }

        [Input("filter")]
        public Input<string>? Filter { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("namespaces")]
        private InputList<string>? _namespaces;
        public InputList<string> Namespaces
        {
            get => _namespaces ?? (_namespaces = new InputList<string>());
            set => _namespaces = value;
        }

        [Input("namespacesObjects")]
        private InputList<Inputs.M3DbM3dbUserConfigRulesMappingNamespacesObjectArgs>? _namespacesObjects;
        public InputList<Inputs.M3DbM3dbUserConfigRulesMappingNamespacesObjectArgs> NamespacesObjects
        {
            get => _namespacesObjects ?? (_namespacesObjects = new InputList<Inputs.M3DbM3dbUserConfigRulesMappingNamespacesObjectArgs>());
            set => _namespacesObjects = value;
        }

        [Input("tags")]
        private InputList<Inputs.M3DbM3dbUserConfigRulesMappingTagArgs>? _tags;
        public InputList<Inputs.M3DbM3dbUserConfigRulesMappingTagArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.M3DbM3dbUserConfigRulesMappingTagArgs>());
            set => _tags = value;
        }

        public M3DbM3dbUserConfigRulesMappingArgs()
        {
        }
        public static new M3DbM3dbUserConfigRulesMappingArgs Empty => new M3DbM3dbUserConfigRulesMappingArgs();
    }
}
