// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class OpenSearchOpensearchUserConfigOpensearchAuthFailureListenersIpRateLimitingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of login attempts allowed before login is blocked. Example: `10`.
        /// </summary>
        [Input("allowedTries")]
        public Input<int>? AllowedTries { get; set; }

        /// <summary>
        /// The duration of time that login remains blocked after a failed login. Example: `600`.
        /// </summary>
        [Input("blockExpirySeconds")]
        public Input<int>? BlockExpirySeconds { get; set; }

        /// <summary>
        /// The maximum number of blocked IP addresses. Example: `100000`.
        /// </summary>
        [Input("maxBlockedClients")]
        public Input<int>? MaxBlockedClients { get; set; }

        /// <summary>
        /// The maximum number of tracked IP addresses that have failed login. Example: `100000`.
        /// </summary>
        [Input("maxTrackedClients")]
        public Input<int>? MaxTrackedClients { get; set; }

        /// <summary>
        /// The window of time in which the value for `allowed_tries` is enforced. Example: `3600`.
        /// </summary>
        [Input("timeWindowSeconds")]
        public Input<int>? TimeWindowSeconds { get; set; }

        /// <summary>
        /// Enum: `ip`. The type of rate limiting.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public OpenSearchOpensearchUserConfigOpensearchAuthFailureListenersIpRateLimitingGetArgs()
        {
        }
        public static new OpenSearchOpensearchUserConfigOpensearchAuthFailureListenersIpRateLimitingGetArgs Empty => new OpenSearchOpensearchUserConfigOpensearchAuthFailureListenersIpRateLimitingGetArgs();
    }
}
