// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Aiven.Inputs
{

    public sealed class ServiceIntegrationMetricsUserConfigSourceMysqlGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration options for Telegraf MySQL input plugin
        /// </summary>
        [Input("telegraf")]
        public Input<Inputs.ServiceIntegrationMetricsUserConfigSourceMysqlTelegrafGetArgs>? Telegraf { get; set; }

        public ServiceIntegrationMetricsUserConfigSourceMysqlGetArgs()
        {
        }
        public static new ServiceIntegrationMetricsUserConfigSourceMysqlGetArgs Empty => new ServiceIntegrationMetricsUserConfigSourceMysqlGetArgs();
    }
}
