// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Gets information about a billing group.
 */
export function getOrganizationBillingGroup(args: GetOrganizationBillingGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetOrganizationBillingGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("aiven:index/getOrganizationBillingGroup:getOrganizationBillingGroup", {
        "billingGroupId": args.billingGroupId,
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrganizationBillingGroup.
 */
export interface GetOrganizationBillingGroupArgs {
    /**
     * ID of the billing group.
     */
    billingGroupId: string;
    /**
     * ID of the organization.
     */
    organizationId: string;
}

/**
 * A collection of values returned by getOrganizationBillingGroup.
 */
export interface GetOrganizationBillingGroupResult {
    /**
     * ID of the billing address.
     */
    readonly billingAddressId: string;
    /**
     * List of billing contact emails.
     */
    readonly billingContactEmails: string[];
    /**
     * Billing currency.
     */
    readonly billingCurrency: string;
    /**
     * List of billing emails.
     */
    readonly billingEmails: string[];
    /**
     * ID of the billing group.
     */
    readonly billingGroupId: string;
    /**
     * Name of the billing group.
     */
    readonly billingGroupName: string;
    /**
     * Custom invoice text.
     */
    readonly customInvoiceText: string;
    /**
     * Resource ID, a composite of organization*id and billing*group_id.
     */
    readonly id: string;
    /**
     * ID of the organization.
     */
    readonly organizationId: string;
    /**
     * ID of the payment method.
     */
    readonly paymentMethodId: string;
    /**
     * ID of the shipping address.
     */
    readonly shippingAddressId: string;
    /**
     * VAT ID.
     */
    readonly vatId: string;
}
/**
 * Gets information about a billing group.
 */
export function getOrganizationBillingGroupOutput(args: GetOrganizationBillingGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOrganizationBillingGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("aiven:index/getOrganizationBillingGroup:getOrganizationBillingGroup", {
        "billingGroupId": args.billingGroupId,
        "organizationId": args.organizationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrganizationBillingGroup.
 */
export interface GetOrganizationBillingGroupOutputArgs {
    /**
     * ID of the billing group.
     */
    billingGroupId: pulumi.Input<string>;
    /**
     * ID of the organization.
     */
    organizationId: pulumi.Input<string>;
}
